package de.dredlich.psm.api.datenschubser.model.mittel;

import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import de.dredlich.psm.api.datenschubser.model.pk.MittelAbgelaufenId;
import jakarta.persistence.*;

import java.util.Date;

/**
 * MittelAbgelaufen generated by hbm2java
 */
@Entity
@Table(name = "MITTEL_ABGELAUFEN")
public class MittelAbgelaufen implements java.io.Serializable, ISetItemPK {

	private MittelAbgelaufenId id;

	private String formulierungArt;

	private Date aufbrauchfrist;

	public MittelAbgelaufen() {
	}

	public MittelAbgelaufen(MittelAbgelaufenId id) {
		this.id = id;
	}

	public MittelAbgelaufen(MittelAbgelaufenId id, String formulierungArt, Date aufbrauchfrist) {
		this.id = id;
		this.formulierungArt = formulierungArt;
		this.aufbrauchfrist = aufbrauchfrist;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
		@AttributeOverride(name = "zulErstmaligAm", column = @Column(name = "ZUL_ERSTMALIG_AM", length = 7)),
		@AttributeOverride(name = "mittelname", column = @Column(name = "MITTELNAME", nullable = false, length = 110)),
		@AttributeOverride(name = "zulEnde", column = @Column(name = "ZUL_ENDE", length = 7)),
		@AttributeOverride(name = "status", column = @Column(name = "STATUS", length = 100))
	})
	public MittelAbgelaufenId getId() {
		return this.id;
	}

	public void setId(MittelAbgelaufenId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (MittelAbgelaufenId) id;
	}



	@Column(name = "FORMULIERUNG_ART", length = 20)
	public String getFormulierungArt() {
		return this.formulierungArt;
	}

	public void setFormulierungArt(String formulierungArt) {
		this.formulierungArt = formulierungArt;
	}

	@Column(name = "AUFBRAUCHFRIST", length = 7)
	public Date getAufbrauchfrist() {
		return this.aufbrauchfrist;
	}

	public void setAufbrauchfrist(Date aufbrauchfrist) {
		this.aufbrauchfrist = aufbrauchfrist;
	}
}
