package de.dredlich.psm.api.datenschubser.model.mittel;

import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import de.dredlich.psm.api.datenschubser.model.pk.MittelAbpackungId;
import jakarta.persistence.*;

/**
 * MittelAbpackung generated by hbm2java
 */
@Entity
@Table(name = "MITTEL_ABPACKUNG")
public class MittelAbpackung implements java.io.Serializable, ISetItemPK {

	private MittelAbpackungId id;

	public MittelAbpackung() {
	}

	public MittelAbpackung(MittelAbpackungId id) {
		this.id = id;
	}
	@EmbeddedId

	@AttributeOverrides({
		@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
		@AttributeOverride(name = "menge", column = @Column(name = "MENGE", nullable = false, length = 20)),
		@AttributeOverride(name = "verpackungsart", column = @Column(name = "VERPACKUNGSART", nullable = false, length = 20)),
		@AttributeOverride(name = "inhaltEinheit", column = @Column(name = "INHALT_EINHEIT", nullable = false, length = 20)),
		@AttributeOverride(name = "verpackungsmaterial", column = @Column(name = "VERPACKUNGSMATERIAL", nullable = false, length = 20)),
		@AttributeOverride(name = "nichtberuflicheAnwender", column = @Column(name = "NICHTBERUFLICHE_ANWENDER", nullable = false, length = 1)),
		@AttributeOverride(name = "anzahl", column = @Column(name = "ANZAHL", nullable = false, length = 20))
	})
	public MittelAbpackungId getId() {
		return this.id;
	}

	public void setId(MittelAbpackungId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (MittelAbpackungId) id;
	}

}
