package de.dredlich.psm.api.datenschubser.model.mittel;

import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import de.dredlich.psm.api.datenschubser.model.pk.MittelGefahrenSymbolId;
import jakarta.persistence.*;

/**
 * MittelGefahrenSymbol generated by hbm2java
 */
@Entity
@Table(name = "MITTEL_GEFAHREN_SYMBOL")
public class MittelGefahrenSymbol implements java.io.Serializable, ISetItemPK {

	private MittelGefahrenSymbolId id;

	public MittelGefahrenSymbol() {}

	public MittelGefahrenSymbol(MittelGefahrenSymbolId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
			@AttributeOverride(name = "gefahrenSymbol", column = @Column(name = "GEFAHREN_SYMBOL", nullable = false, length = 20)) })
	public MittelGefahrenSymbolId getId() {
		return this.id;
	}

	public void setId(MittelGefahrenSymbolId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (MittelGefahrenSymbolId) id;
	}

}
