package de.dredlich.psm.api.datenschubser.model.mittel;

import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import de.dredlich.psm.api.datenschubser.model.pk.MittelVertriebId;
import jakarta.persistence.*;

/**
 * MittelVertrieb generated by hbm2java
 */
@Entity
@Table(name = "MITTEL_VERTRIEB")
public class MittelVertrieb implements java.io.Serializable, ISetItemPK {

	private MittelVertriebId id;
	private String vertriebsfirma;

	public MittelVertrieb() {
	}

	public MittelVertrieb(MittelVertriebId id,  String vertriebsfirma) {
		this.id = id;
		this.vertriebsfirma = vertriebsfirma;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
			@AttributeOverride(name = "vertriebsfirmaNr", column = @Column(name = "VERTRIEBSFIRMA_NR", nullable = false, precision = 22, scale = 0)) })
	public MittelVertriebId getId() {
		return this.id;
	}

	public void setId(MittelVertriebId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (MittelVertriebId) id;
	}

	@Column(name = "VERTRIEBSFIRMA", length = 20)
	public String getVertriebsfirma() {
		return this.vertriebsfirma;
	}

	public void setVertriebsfirma(String vertriebsfirma) {
		this.vertriebsfirma = vertriebsfirma;
	}

}
