package de.dredlich.psm.api.datenschubser.model.ghs;

import de.dredlich.psm.api.datenschubser.model.pk.GhsGefahrenhinweiseId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * GhsGefahrenhinweise generated by hbm2java
 */
@Entity
@Table(name = "GHS_GEFAHRENHINWEISE")
public class GhsGefahrenhinweise implements java.io.Serializable, ISetItemPK {

	private GhsGefahrenhinweiseId id;

	public GhsGefahrenhinweise() {
	}

	public GhsGefahrenhinweise(GhsGefahrenhinweiseId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
		@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
		@AttributeOverride(name = "gefahrenhinweis", column = @Column(name = "GEFAHRENHINWEIS", nullable = false, length = 20))
	})
	public GhsGefahrenhinweiseId getId() {
		return this.id;
	}

	public void setId(GhsGefahrenhinweiseId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (GhsGefahrenhinweiseId) id;
	}

}
