package de.dredlich.psm.api.datenschubser.model.ghs;

import de.dredlich.psm.api.datenschubser.model.pk.GhsGefahrensymboleId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * GhsGefahrensymbole generated by hbm2java
 */
@Entity
@Table(name = "GHS_GEFAHRENSYMBOLE")
public class GhsGefahrensymbole implements java.io.Serializable, ISetItemPK {

	private GhsGefahrensymboleId id;

	public GhsGefahrensymbole() {
	}

	public GhsGefahrensymbole(GhsGefahrensymboleId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
		@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
		@AttributeOverride(name = "gefahrensymbol", column = @Column(name = "GEFAHRENSYMBOL", nullable = false, length = 20))
	})
	public GhsGefahrensymboleId getId() {
		return this.id;
	}

	public void setId(GhsGefahrensymboleId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (GhsGefahrensymboleId) id;
	}


}
