package de.dredlich.psm.api.datenschubser.model.ghs;

import de.dredlich.psm.api.datenschubser.model.pk.GhsSicherheitshinweiseId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * GhsSicherheitshinweise generated by hbm2java
 */
@Entity
@Table(name = "GHS_SICHERHEITSHINWEISE")
public class GhsSicherheitshinweise implements java.io.Serializable, ISetItemPK {

	private GhsSicherheitshinweiseId id;

	public GhsSicherheitshinweise() {
	}

	public GhsSicherheitshinweise(GhsSicherheitshinweiseId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
		@AttributeOverride(name = "sicherheitshinweis", column = @Column(name = "SICHERHEITSHINWEIS", nullable = false, length = 20))
	})
	public GhsSicherheitshinweiseId getId() {
		return this.id;
	}

	public void setId(GhsSicherheitshinweiseId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (GhsSicherheitshinweiseId) id;
	}

}
