package de.dredlich.psm.api.datenschubser.model.ghs;

import de.dredlich.psm.api.datenschubser.model.pk.GhsSignalwoerterId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * GhsSignalwoerter generated by hbm2java
 */
@Entity
@Table(name = "GHS_SIGNALWOERTER")
public class GhsSignalwoerter implements java.io.Serializable, ISetItemPK {

	private GhsSignalwoerterId id;

	public GhsSignalwoerter() {}

	public GhsSignalwoerter(GhsSignalwoerterId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
		@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
		@AttributeOverride(name = "signalwort", column = @Column(name = "SIGNALWORT", nullable = false, length = 20))
	})
	public GhsSignalwoerterId getId() {
		return this.id;
	}

	public void setId(GhsSignalwoerterId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (GhsSignalwoerterId) id;
	}

}
