package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * AntragId generated by hbm2java
 */
@Embeddable
public class AntragId implements java.io.Serializable, ICompPK {

	@Column(name = "KENNR", nullable = false, length = 9)
	private String kennr;
	@Column(name = "ANTRAGNR", nullable = false, length = 2)
	private String antragnr;

	public AntragId() {
	}

	public AntragId(String kennr, String antragnr) {
		this.kennr = kennr;
		this.antragnr = antragnr;
	}
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	public String getAntragnr() {
		return this.antragnr;
	}

	public void setAntragnr(String antragnr) {
		this.antragnr = antragnr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AntragId))
			return false;
		AntragId castOther = (AntragId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null && castOther.getKennr() != null
				&& this.getKennr().equals(castOther.getKennr())))
				&& ((this.getAntragnr() == castOther.getAntragnr()) || (this.getAntragnr() != null
						&& castOther.getAntragnr() != null && this.getAntragnr().equals(castOther.getAntragnr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getAntragnr() == null ? 0 : this.getAntragnr().hashCode());
		return result;
	}

}
