package de.dredlich.psm.api.datenschubser.model.pk;

import java.math.BigDecimal;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * AwgAufwandId generated by hbm2java
 */
@Embeddable
public class AwgAufwandId implements java.io.Serializable, ICompPK {

	private String awgId;
	private String aufwandbedingung;
	private BigDecimal sortierNr;

	public AwgAufwandId() {
	}

	public AwgAufwandId(String awgId, String aufwandbedingung, BigDecimal sortierNr) {
		this.awgId = awgId;
		this.aufwandbedingung = aufwandbedingung;
		this.sortierNr = sortierNr;
	}

	@Column(name = "AWG_ID", nullable = false, length = 16)
	public String getAwgId() {
		return this.awgId;
	}

	public void setAwgId(String awgId) {
		this.awgId = awgId;
	}

	@Column(name = "AUFWANDBEDINGUNG", nullable = false, length = 20)
	public String getAufwandbedingung() {
		return this.aufwandbedingung;
	}

	public void setAufwandbedingung(String aufwandbedingung) {
		this.aufwandbedingung = aufwandbedingung;
	}

	@Column(name = "SORTIER_NR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSortierNr() {
		return this.sortierNr;
	}

	public void setSortierNr(BigDecimal sortierNr) {
		this.sortierNr = sortierNr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AwgAufwandId))
			return false;
		AwgAufwandId castOther = (AwgAufwandId) other;

		return ((this.getAwgId() == castOther.getAwgId()) || (this.getAwgId() != null && castOther.getAwgId() != null
				&& this.getAwgId().equals(castOther.getAwgId())))
				&& ((this.getAufwandbedingung() == castOther.getAufwandbedingung())
						|| (this.getAufwandbedingung() != null && castOther.getAufwandbedingung() != null
								&& this.getAufwandbedingung().equals(castOther.getAufwandbedingung())))
				&& ((this.getSortierNr() == castOther.getSortierNr()) || (this.getSortierNr() != null
						&& castOther.getSortierNr() != null && this.getSortierNr().equals(castOther.getSortierNr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAwgId() == null ? 0 : this.getAwgId().hashCode());
		result = 37 * result + (getAufwandbedingung() == null ? 0 : this.getAufwandbedingung().hashCode());
		result = 37 * result + (getSortierNr() == null ? 0 : this.getSortierNr().hashCode());
		return result;
	}

}
