package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * AwgBemId generated by hbm2java
 */
@Embeddable
public class AwgBemId implements java.io.Serializable, ICompPK {

	private String awgId;
	private String auflageBem;

	public AwgBemId() {
	}

	public AwgBemId(String awgId, String auflageBem) {
		this.awgId = awgId;
		this.auflageBem = auflageBem;
	}

	@Column(name = "AWG_ID", nullable = false, length = 16)
	public String getAwgId() {
		return this.awgId;
	}

	public void setAwgId(String awgId) {
		this.awgId = awgId;
	}

	@Column(name = "AUFLAGE_BEM", nullable = false, length = 20)
	public String getAuflageBem() {
		return this.auflageBem;
	}

	public void setAuflageBem(String auflageBem) {
		this.auflageBem = auflageBem;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AwgBemId))
			return false;
		AwgBemId castOther = (AwgBemId) other;

		return ((this.getAwgId() == castOther.getAwgId()) || (this.getAwgId() != null && castOther.getAwgId() != null
				&& this.getAwgId().equals(castOther.getAwgId())))
				&& ((this.getAuflageBem() == castOther.getAuflageBem())
						|| (this.getAuflageBem() != null && castOther.getAuflageBem() != null
								&& this.getAuflageBem().equals(castOther.getAuflageBem())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAwgId() == null ? 0 : this.getAwgId().hashCode());
		result = 37 * result + (getAuflageBem() == null ? 0 : this.getAuflageBem().hashCode());
		return result;
	}

}
