package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * AwgKulturId generated by hbm2java
 */
@Embeddable
public class AwgKulturId implements java.io.Serializable, ICompPK {

	private String awgId;
	private String kultur;

	public AwgKulturId() {
	}

	public AwgKulturId(String awgId, String kultur) {
		this.awgId = awgId;
		this.kultur = kultur;
	}

	@Column(name = "AWG_ID", nullable = false, length = 16)
	public String getAwgId() {
		return this.awgId;
	}

	public void setAwgId(String awgId) {
		this.awgId = awgId;
	}

	@Column(name = "KULTUR", nullable = false, length = 20)
	public String getKultur() {
		return this.kultur;
	}

	public void setKultur(String kultur) {
		this.kultur = kultur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AwgKulturId))
			return false;
		AwgKulturId castOther = (AwgKulturId) other;

		return ((this.getAwgId() == castOther.getAwgId()) || (this.getAwgId() != null && castOther.getAwgId() != null
				&& this.getAwgId().equals(castOther.getAwgId())))
				&& ((this.getKultur() == castOther.getKultur()) || (this.getKultur() != null
						&& castOther.getKultur() != null && this.getKultur().equals(castOther.getKultur())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAwgId() == null ? 0 : this.getAwgId().hashCode());
		result = 37 * result + (getKultur() == null ? 0 : this.getKultur().hashCode());
		return result;
	}

}
