package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * AwgPartnerId generated by hbm2java
 */
@Embeddable
public class AwgPartnerId implements java.io.Serializable, ICompPK {

	private String awgId;
	private String partnerKennr;

	public AwgPartnerId() {
	}

	public AwgPartnerId(String awgId, String partnerKennr) {
		this.awgId = awgId;
		this.partnerKennr = partnerKennr;
	}

	@Column(name = "AWG_ID", nullable = false, length = 16)
	public String getAwgId() {
		return this.awgId;
	}

	public void setAwgId(String awgId) {
		this.awgId = awgId;
	}

	@Column(name = "PARTNER_KENNR", nullable = false, length = 9)
	public String getPartnerKennr() {
		return this.partnerKennr;
	}

	public void setPartnerKennr(String partnerKennr) {
		this.partnerKennr = partnerKennr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AwgPartnerId))
			return false;
		AwgPartnerId castOther = (AwgPartnerId) other;

		return ((this.getAwgId() == castOther.getAwgId()) || (this.getAwgId() != null && castOther.getAwgId() != null
				&& this.getAwgId().equals(castOther.getAwgId())))
				&& ((this.getPartnerKennr() == castOther.getPartnerKennr())
						|| (this.getPartnerKennr() != null && castOther.getPartnerKennr() != null
								&& this.getPartnerKennr().equals(castOther.getPartnerKennr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAwgId() == null ? 0 : this.getAwgId().hashCode());
		result = 37 * result + (getPartnerKennr() == null ? 0 : this.getPartnerKennr().hashCode());
		return result;
	}

}
