package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * AwgVerwendungszweckId generated by hbm2java
 */
@Embeddable
public class AwgVerwendungszweckId implements java.io.Serializable, ICompPK {

	private String awgId;
	private String verwendungszweck;

	public AwgVerwendungszweckId() {
	}

	public AwgVerwendungszweckId(String awgId, String verwendungszweck) {
		this.awgId = awgId;
		this.verwendungszweck = verwendungszweck;
	}

	@Column(name = "AWG_ID", nullable = false, length = 16)
	public String getAwgId() {
		return this.awgId;
	}
	public void setAwgId(String awgId) {
		this.awgId = awgId;
	}

	@Column(name = "VERWENDUNGSZWECK", nullable = false, length = 20)
	public String getVerwendungszweck() {
		return this.verwendungszweck;
	}
	public void setVerwendungszweck(String verwendungszweck) {
		this.verwendungszweck = verwendungszweck;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AwgVerwendungszweckId))
			return false;
		AwgVerwendungszweckId castOther = (AwgVerwendungszweckId) other;

		return ((this.getAwgId() == castOther.getAwgId()) || (this.getAwgId() != null
						&& castOther.getAwgId() != null && this.getAwgId().equals(castOther.getAwgId())))
				&& ((this.getVerwendungszweck() == castOther.getVerwendungszweck())
						|| (this.getVerwendungszweck() != null && castOther.getVerwendungszweck() != null
								&& this.getVerwendungszweck().equals(castOther.getVerwendungszweck())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAwgId() == null ? 0 : this.getAwgId().hashCode());
		result = 37 * result + (getVerwendungszweck() == null ? 0 : this.getVerwendungszweck().hashCode());
		return result;
	}

}
