package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * AwgZeitpunktId generated by hbm2java
 */
@Embeddable
public class AwgZeitpunktId implements java.io.Serializable, ICompPK {

	private String awgId;
	private String zeitpunkt;

	public AwgZeitpunktId() {
	}

	public AwgZeitpunktId(String awgId, String zeitpunkt) {
		this.awgId = awgId;
		this.zeitpunkt = zeitpunkt;
	}

	@Column(name = "AWG_ID", nullable = false, length = 16)
	public String getAwgId() {
		return this.awgId;
	}

	public void setAwgId(String awgId) {
		this.awgId = awgId;
	}

	@Column(name = "ZEITPUNKT", nullable = false, length = 20)
	public String getZeitpunkt() {
		return this.zeitpunkt;
	}

	public void setZeitpunkt(String zeitpunkt) {
		this.zeitpunkt = zeitpunkt;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AwgZeitpunktId))
			return false;
		AwgZeitpunktId castOther = (AwgZeitpunktId) other;

		return ((this.getAwgId() == castOther.getAwgId()) || (this.getAwgId() != null && castOther.getAwgId() != null
				&& this.getAwgId().equals(castOther.getAwgId())))
				&& ((this.getZeitpunkt() == castOther.getZeitpunkt()) || (this.getZeitpunkt() != null
						&& castOther.getZeitpunkt() != null && this.getZeitpunkt().equals(castOther.getZeitpunkt())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAwgId() == null ? 0 : this.getAwgId().hashCode());
		result = 37 * result + (getZeitpunkt() == null ? 0 : this.getZeitpunkt().hashCode());
		return result;
	}

}
