package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * GhsGefahrensymboleId generated by hbm2java
 */
@Embeddable
public class GhsGefahrensymboleId implements java.io.Serializable, ICompPK {

	private String kennr;
	private String gefahrensymbol;

	public GhsGefahrensymboleId() {
	}

	public GhsGefahrensymboleId(String kennr, String gefahrensymbol) {
		this.kennr = kennr;
		this.gefahrensymbol = gefahrensymbol;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "GEFAHRENSYMBOL", nullable = false, length = 20)
	public String getGefahrensymbol() {
		return this.gefahrensymbol;
	}

	public void setGefahrensymbol(String gefahrensymbol) {
		this.gefahrensymbol = gefahrensymbol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GhsGefahrensymboleId))
			return false;
		GhsGefahrensymboleId castOther = (GhsGefahrensymboleId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null
						&& castOther.getKennr() != null && this.getKennr().equals(castOther.getKennr())))
				&& ((this.getGefahrensymbol() == castOther.getGefahrensymbol())
						|| (this.getGefahrensymbol() != null && castOther.getGefahrensymbol() != null
								&& this.getGefahrensymbol().equals(castOther.getGefahrensymbol())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getGefahrensymbol() == null ? 0 : this.getGefahrensymbol().hashCode());
		return result;
	}

}
