package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * GhsGefahrenhinweiseId generated by hbm2java
 */
@Embeddable
public class GhsGefahrenhinweiseId implements java.io.Serializable, ICompPK {

	private String kennr;
	private String gefahrenhinweis;

	public GhsGefahrenhinweiseId() {
	}

	public GhsGefahrenhinweiseId(String kennr, String gefahrenhinweis) {
		this.kennr = kennr;
		this.gefahrenhinweis = gefahrenhinweis;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "GEFAHRENHINWEIS", nullable = false, length = 20)
	public String getGefahrenhinweis() {
		return this.gefahrenhinweis;
	}

	public void setGefahrenhinweis(String gefahrenhinweis) {
		this.gefahrenhinweis = gefahrenhinweis;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GhsGefahrenhinweiseId))
			return false;
		GhsGefahrenhinweiseId castOther = (GhsGefahrenhinweiseId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null
						&& castOther.getKennr() != null && this.getKennr().equals(castOther.getKennr())))
				&& ((this.getGefahrenhinweis() == castOther.getGefahrenhinweis())
						|| (this.getGefahrenhinweis() != null && castOther.getGefahrenhinweis() != null
								&& this.getGefahrenhinweis().equals(castOther.getGefahrenhinweis())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getGefahrenhinweis() == null ? 0 : this.getGefahrenhinweis().hashCode());
		return result;
	}

}
