package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * GhsSignalwoerterId generated by hbm2java
 */
@Embeddable
public class GhsSignalwoerterId implements java.io.Serializable, ICompPK {

	private String kennr;
	private String signalwort;

	public GhsSignalwoerterId() {
	}

	public GhsSignalwoerterId(String kennr, String signalwort) {
		this.kennr = kennr;
		this.signalwort = signalwort;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "SIGNALWORT", nullable = false, length = 20)
	public String getSignalwort() {
		return this.signalwort;
	}

	public void setSignalwort(String signalwort) {
		this.signalwort = signalwort;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GhsSignalwoerterId))
			return false;
		GhsSignalwoerterId castOther = (GhsSignalwoerterId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null
						&& castOther.getKennr() != null && this.getKennr().equals(castOther.getKennr())))
				&& ((this.getSignalwort() == castOther.getSignalwort())
						|| (this.getSignalwort() != null && castOther.getSignalwort() != null
								&& this.getSignalwort().equals(castOther.getSignalwort())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getSignalwort() == null ? 0 : this.getSignalwort().hashCode());
		return result;
	}

}
