package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * GhsSicherheitshinweiseId generated by hbm2java
 */
@Embeddable
public class GhsSicherheitshinweiseId implements java.io.Serializable, ICompPK {

	private String kennr;
	private String sicherheitshinweis;

	public GhsSicherheitshinweiseId() {
	}

	public GhsSicherheitshinweiseId(String kennr, String sicherheitshinweis) {
		this.kennr = kennr;
		this.sicherheitshinweis = sicherheitshinweis;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "SICHERHEITSHINWEIS", nullable = false, length = 20)
	public String getSicherheitshinweis() {
		return this.sicherheitshinweis;
	}

	public void setSicherheitshinweis(String sicherheitshinweis) {
		this.sicherheitshinweis = sicherheitshinweis;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GhsSicherheitshinweiseId))
			return false;
		GhsSicherheitshinweiseId castOther = (GhsSicherheitshinweiseId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null
						&& castOther.getKennr() != null && this.getKennr().equals(castOther.getKennr())))
				&& ((this.getSicherheitshinweis() == castOther.getSicherheitshinweis())
						|| (this.getSicherheitshinweis() != null && castOther.getSicherheitshinweis() != null
								&& this.getSicherheitshinweis().equals(castOther.getSicherheitshinweis())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getSicherheitshinweis() == null ? 0 : this.getSicherheitshinweis().hashCode());
		return result;
	}

}
