package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * KodeId generated by hbm2java
 */
@Embeddable
public class KodeId implements java.io.Serializable, ICompPK {

	private String kode;
	private Short kodeliste;
	private String sprache;

	public KodeId() {
	}

	public KodeId(String kode, Short kodeliste, String sprache) {
		this.kode = kode;
		this.kodeliste = kodeliste;
		this.sprache = sprache;
	}

	@Column(name = "KODE", nullable = false, length = 20)
	public String getKode() {
		return this.kode;
	}

	public void setKode(String kode) {
		this.kode = kode;
	}

	@Column(name = "KODELISTE", nullable = false, precision = 3, scale = 0)
	public Short getKodeliste() {
		return this.kodeliste;
	}

	public void setKodeliste(Short kodeliste) {
		this.kodeliste = kodeliste;
	}

	@Column(name = "SPRACHE", nullable = false, length = 20)
	public String getSprache() {
		return this.sprache;
	}

	public void setSprache(String sprache) {
		this.sprache = sprache;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KodeId))
			return false;
		KodeId castOther = (KodeId) other;

		return ((this.getKode() == castOther.getKode()) || (this.getKode() != null && castOther.getKode() != null
				&& this.getKode().equals(castOther.getKode()))) && (this.getKodeliste() == castOther.getKodeliste())
				&& ((this.getSprache() == castOther.getSprache()) || (this.getSprache() != null
						&& castOther.getSprache() != null && this.getSprache().equals(castOther.getSprache())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKode() == null ? 0 : this.getKode().hashCode());
		result = 37 * result + this.getKodeliste();
		result = 37 * result + (getSprache() == null ? 0 : this.getSprache().hashCode());
		return result;
	}

}
