package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * KulturGruppeId generated by hbm2java
 */
@Embeddable
public class KulturGruppeId implements java.io.Serializable, ICompPK {

	private String kulturGruppe;
	private String kultur;

	public KulturGruppeId() {
	}

	public KulturGruppeId(String kulturGruppe, String kultur) {
		this.kulturGruppe = kulturGruppe;
		this.kultur = kultur;
	}

	@Column(name = "KULTUR_GRUPPE", nullable = false, length = 20)
	public String getKulturGruppe() {
		return this.kulturGruppe;
	}

	public void setKulturGruppe(String kulturGruppe) {
		this.kulturGruppe = kulturGruppe;
	}

	@Column(name = "KULTUR", nullable = false, length = 20)
	public String getKultur() {
		return this.kultur;
	}

	public void setKultur(String kultur) {
		this.kultur = kultur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof KulturGruppeId))
			return false;
		KulturGruppeId castOther = (KulturGruppeId) other;

		return ((this.getKulturGruppe() == castOther.getKulturGruppe()) || (this.getKulturGruppe() != null
				&& castOther.getKulturGruppe() != null && this.getKulturGruppe().equals(castOther.getKulturGruppe())))
				&& ((this.getKultur() == castOther.getKultur()) || (this.getKultur() != null
						&& castOther.getKultur() != null && this.getKultur().equals(castOther.getKultur())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKulturGruppe() == null ? 0 : this.getKulturGruppe().hashCode());
		result = 37 * result + (getKultur() == null ? 0 : this.getKultur().hashCode());
		return result;
	}

}
