package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * MittelGefahrenSymbolId generated by hbm2java
 */
@Embeddable
public class MittelGefahrenSymbolId implements java.io.Serializable, ICompPK {

	private String kennr;
	private String gefahrenSymbol;

	public MittelGefahrenSymbolId() {
	}

	public MittelGefahrenSymbolId(String kennr, String gefahrenSymbol) {
		this.kennr = kennr;
		this.gefahrenSymbol = gefahrenSymbol;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "GEFAHREN_SYMBOL", nullable = false, length = 20)
	public String getGefahrenSymbol() {
		return this.gefahrenSymbol;
	}

	public void setGefahrenSymbol(String gefahrenSymbol) {
		this.gefahrenSymbol = gefahrenSymbol;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MittelGefahrenSymbolId))
			return false;
		MittelGefahrenSymbolId castOther = (MittelGefahrenSymbolId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null && castOther.getKennr() != null
				&& this.getKennr().equals(castOther.getKennr())))
				&& ((this.getGefahrenSymbol() == castOther.getGefahrenSymbol())
						|| (this.getGefahrenSymbol() != null && castOther.getGefahrenSymbol() != null
								&& this.getGefahrenSymbol().equals(castOther.getGefahrenSymbol())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getGefahrenSymbol() == null ? 0 : this.getGefahrenSymbol().hashCode());
		return result;
	}

}
