package de.dredlich.psm.api.datenschubser.model.pk;
// Generated 21.08.2021, 19:02:40 by Hibernate Tools 5.2.12.Final

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * MittelVertriebId generated by hbm2java
 */
@Embeddable
public class MittelVertriebId implements java.io.Serializable, ICompPK {

	private String kennr;
	private BigDecimal vertriebsfirmaNr;

	public MittelVertriebId() {
	}

	public MittelVertriebId(String kennr, BigDecimal vertriebsfirmaNr) {
		this.kennr = kennr;
		this.vertriebsfirmaNr = vertriebsfirmaNr;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "VERTRIEBSFIRMA_NR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getVertriebsfirmaNr() {
		return this.vertriebsfirmaNr;
	}

	public void setVertriebsfirmaNr(BigDecimal vertriebsfirmaNr) {
		this.vertriebsfirmaNr = vertriebsfirmaNr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MittelVertriebId))
			return false;
		MittelVertriebId castOther = (MittelVertriebId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null && castOther.getKennr() != null
				&& this.getKennr().equals(castOther.getKennr())))
				&& ((this.getVertriebsfirmaNr() == castOther.getVertriebsfirmaNr())
						|| (this.getVertriebsfirmaNr() != null && castOther.getVertriebsfirmaNr() != null
								&& this.getVertriebsfirmaNr().equals(castOther.getVertriebsfirmaNr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getVertriebsfirmaNr() == null ? 0 : this.getVertriebsfirmaNr().hashCode());
		return result;
	}

}
