package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * MittelWirkbereichId generated by hbm2java
 */
@Embeddable
public class MittelWirkbereichId implements java.io.Serializable, ICompPK {

	private String kennr;
	private String wirkungsbereich;

	public MittelWirkbereichId() {
	}

	public MittelWirkbereichId(String kennr, String wirkungsbereich) {
		this.kennr = kennr;
		this.wirkungsbereich = wirkungsbereich;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "WIRKUNGSBEREICH", nullable = false, length = 20)
	public String getWirkungsbereich() {
		return this.wirkungsbereich;
	}

	public void setWirkungsbereich(String wirkungsbereich) {
		this.wirkungsbereich = wirkungsbereich;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MittelWirkbereichId))
			return false;
		MittelWirkbereichId castOther = (MittelWirkbereichId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null && castOther.getKennr() != null
				&& this.getKennr().equals(castOther.getKennr())))
				&& ((this.getWirkungsbereich() == castOther.getWirkungsbereich())
						|| (this.getWirkungsbereich() != null && castOther.getWirkungsbereich() != null
								&& this.getWirkungsbereich().equals(castOther.getWirkungsbereich())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getWirkungsbereich() == null ? 0 : this.getWirkungsbereich().hashCode());
		return result;
	}

}
