package de.dredlich.psm.api.datenschubser.model.pk;

import de.dredlich.psm.api.datenschubser.converter.BooleanToStringConverter;

import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Embeddable;

/**
 * MittelAbpackungId generated by hbm2java
 */
@Embeddable
public class MittelAbpackungId implements java.io.Serializable, ICompPK {

	private String kennr;
	private String menge;
	private String verpackungsart;
	private String inhaltEinheit;
	private String verpackungsmaterial;
	private Boolean nichtberuflicheAnwender;
	private String anzahl;

	public MittelAbpackungId() {
	}

	public MittelAbpackungId(String kennr, String menge, String verpackungsart, String inhaltEinheit,
			String verpackungsmaterial, Boolean nichtberuflicheAnwender, String anzahl) {
		this.kennr = kennr;
		this.menge = menge;
		this.verpackungsart = verpackungsart;
		this.inhaltEinheit = inhaltEinheit;
		this.verpackungsmaterial = verpackungsmaterial;
		this.nichtberuflicheAnwender = nichtberuflicheAnwender;
		this.anzahl = anzahl;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "MENGE", nullable = false, length = 20)
	public String getMenge() {
		return this.menge;
	}

	public void setMenge(String menge) {
		this.menge = menge;
	}

	@Column(name = "VERPACKUNGSART", nullable = false, length = 20)
	public String getVerpackungsart() {
		return this.verpackungsart;
	}

	public void setVerpackungsart(String verpackungsart) {
		this.verpackungsart = verpackungsart;
	}

	@Column(name = "INHALT_EINHEIT", nullable = false, length = 20)
	public String getInhaltEinheit() {
		return this.inhaltEinheit;
	}

	public void setInhaltEinheit(String inhaltEinheit) {
		this.inhaltEinheit = inhaltEinheit;
	}


	@Column(name = "VERPACKUNGSMATERIAL", nullable = false, length = 20)
	public String getVerpackungsmaterial() {
		return this.verpackungsmaterial;
	}
	public void setVerpackungsmaterial(String verpackungsmaterial) {
		this.verpackungsmaterial = verpackungsmaterial;
	}

	@Convert(converter= BooleanToStringConverter.class)
	@Column(name = "NICHTBERUFLICHE_ANWENDER", nullable = false, length = 1)
	public Boolean getNichtberuflicheAnwender() {
		return this.nichtberuflicheAnwender;
	}

	@Convert(converter=BooleanToStringConverter.class)
	public void setNichtberuflicheAnwender(Boolean nichtberuflicheAnwender) {
		this.nichtberuflicheAnwender = nichtberuflicheAnwender;
	}

	@Column(name = "ANZAHL", nullable = false, length = 20)
	public String getAnzahl() {
		return this.anzahl;
	}

	public void setAnzahl(String anzahl) {
		this.anzahl = anzahl;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MittelAbpackungId))
			return false;
		MittelAbpackungId castOther = (MittelAbpackungId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null
						&& castOther.getKennr() != null && this.getKennr().equals(castOther.getKennr())))
				&& ((this.getMenge() == castOther.getMenge()) || (this.getMenge() != null
						&& castOther.getMenge() != null && this.getMenge().equals(castOther.getMenge())))
				&& ((this.getVerpackungsart() == castOther.getVerpackungsart())
						|| (this.getVerpackungsart() != null && castOther.getVerpackungsart() != null
								&& this.getVerpackungsart().equals(castOther.getVerpackungsart())))
				&& ((this.getInhaltEinheit() == castOther.getInhaltEinheit())
						|| (this.getInhaltEinheit() != null && castOther.getInhaltEinheit() != null
								&& this.getInhaltEinheit().equals(castOther.getInhaltEinheit())))
				&& ((this.getVerpackungsmaterial() == castOther.getVerpackungsmaterial())
						|| (this.getVerpackungsmaterial() != null && castOther.getVerpackungsmaterial() != null
								&& this.getVerpackungsmaterial().equals(castOther.getVerpackungsmaterial())))
				&& (this.getNichtberuflicheAnwender() == castOther.getNichtberuflicheAnwender())
				&& ((this.getAnzahl() == castOther.getAnzahl()) || (this.getAnzahl() != null
						&& castOther.getAnzahl() != null && this.getAnzahl().equals(castOther.getAnzahl())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getMenge() == null ? 0 : this.getMenge().hashCode());
		result = 37 * result + (getVerpackungsart() == null ? 0 : this.getVerpackungsart().hashCode());
		result = 37 * result + (getInhaltEinheit() == null ? 0 : this.getInhaltEinheit().hashCode());
		result = 37 * result + (getVerpackungsmaterial() == null ? 0 : this.getVerpackungsmaterial().hashCode());
		result = 37 * result + (getAnzahl() == null ? 0 : this.getAnzahl().hashCode());
		return result;
	}

}
