package de.dredlich.psm.api.datenschubser.model.pk;

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * MittelAbgelaufenId generated by hbm2java
 */
@Embeddable
public class MittelAbgelaufenId implements java.io.Serializable, ICompPK {

	private String kennr;
	private Date zulErstmaligAm;
	private String mittelname;
	private Date zulEnde;
	private String status;

	public MittelAbgelaufenId() {
	}

	public MittelAbgelaufenId(String kennr, Date zulErstmaligAm, String mittelname, Date zulEnde, String status) {
		this.kennr = kennr;
		this.zulErstmaligAm = zulErstmaligAm;
		this.mittelname = mittelname;
		this.zulEnde = zulEnde;
		this.status = status;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "ZUL_ERSTMALIG_AM", length = 7)
	public Date getZulErstmaligAm() {
		return this.zulErstmaligAm;
	}

	public void setZulErstmaligAm(Date zulErstmaligAm) {
		this.zulErstmaligAm = zulErstmaligAm;
	}

	@Column(name = "MITTELNAME", nullable = false, length = 110)
	public String getMittelname() {
		return this.mittelname;
	}

	public void setMittelname(String mittelname) {
		this.mittelname = mittelname;
	}

	@Column(name = "ZUL_ENDE", length = 7)
	public Date getZulEnde() {
		return this.zulEnde;
	}

	public void setZulEnde(Date zulEnde) {
		this.zulEnde = zulEnde;
	}

	@Column(name = "STATUS", length = 100)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MittelAbgelaufenId))
			return false;
		MittelAbgelaufenId castOther = (MittelAbgelaufenId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null
						&& castOther.getKennr() != null && this.getKennr().equals(castOther.getKennr())))
				&& ((this.getZulErstmaligAm() == castOther.getZulErstmaligAm())
						|| (this.getZulErstmaligAm() != null && castOther.getZulErstmaligAm() != null
								&& this.getZulErstmaligAm().equals(castOther.getZulErstmaligAm())))
				&& ((this.getMittelname() == castOther.getMittelname()) || (this.getMittelname() != null
						&& castOther.getMittelname() != null && this.getMittelname().equals(castOther.getMittelname())))
				&& ((this.getZulEnde() == castOther.getZulEnde()) || (this.getZulEnde() != null
						&& castOther.getZulEnde() != null && this.getZulEnde().equals(castOther.getZulEnde())))
				&& ((this.getStatus() == castOther.getStatus()) || (this.getStatus() != null
						&& castOther.getStatus() != null && this.getStatus().equals(castOther.getStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getZulErstmaligAm() == null ? 0 : this.getZulErstmaligAm().hashCode());
		result = 37 * result + (getMittelname() == null ? 0 : this.getMittelname().hashCode());
		result = 37 * result + (getZulEnde() == null ? 0 : this.getZulEnde().hashCode());
		result = 37 * result + (getStatus() == null ? 0 : this.getStatus().hashCode());
		return result;
	}

}
