package de.dredlich.psm.api.datenschubser.model.pk;

import de.dredlich.psm.api.datenschubser.converter.BooleanToStringConverter;

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Convert;
import jakarta.persistence.Embeddable;

/**
 * ParallelimportGueltigId generated by hbm2java
 */
@Embeddable
public class ParallelimportGueltigId implements java.io.Serializable, ICompPK {

	private String piPsmnr;
	private String piReferenzKennr;
	private String piKennziffer;
	private String piStatus;
	private String importeurTxt;
	private String piMittelname;
	private Date gueltig;
	private String piBescheidnr;
	private Date bescheidDatum;
	private Boolean bescheinigung;
	private String mittelname;
	private BigDecimal importeurNr;

	public ParallelimportGueltigId() {
	}

	public ParallelimportGueltigId(String piPsmnr) {
		this.piPsmnr = piPsmnr;
	}

	public ParallelimportGueltigId(String piPsmnr, String piReferenzKennr, String piKennziffer,
			String piStatus, String importeurTxt, String piMittelname, Date gueltig, String piBescheidnr,
			Date bescheidDatum, Boolean bescheinigung, String mittelname, BigDecimal importeurNr) {
		this.piPsmnr = piPsmnr;
		this.piReferenzKennr = piReferenzKennr;
		this.piKennziffer = piKennziffer;
		this.piStatus = piStatus;
		this.importeurTxt = importeurTxt;
		this.piMittelname = piMittelname;
		this.gueltig = gueltig;
		this.piBescheidnr = piBescheidnr;
		this.bescheidDatum = bescheidDatum;
		this.bescheinigung = bescheinigung;
		this.mittelname = mittelname;
		this.importeurNr = importeurNr;
	}

	@Column(name = "PI_PSMNR", nullable = false, length = 7)
	public String getPiPsmnr() {
		return this.piPsmnr;
	}

	public void setPiPsmnr(String piPsmnr) {
		this.piPsmnr = piPsmnr;
	}

	@Column(name = "PI_REFERENZ_KENNR", length = 9)
	public String getPiReferenzKennr() {
		return this.piReferenzKennr;
	}

	public void setPiReferenzKennr(String piReferenzKennr) {
		this.piReferenzKennr = piReferenzKennr;
	}

	@Column(name = "PI_KENNZIFFER", length = 3)
	public String getPiKennziffer() {
		return this.piKennziffer;
	}

	public void setPiKennziffer(String piKennziffer) {
		this.piKennziffer = piKennziffer;
	}

	@Column(name = "PI_STATUS", length = 20)
	public String getPiStatus() {
		return this.piStatus;
	}

	public void setPiStatus(String piStatus) {
		this.piStatus = piStatus;
	}

	@Column(name = "IMPORTEUR_TXT", length = 300)
	public String getImporteurTxt() {
		return this.importeurTxt;
	}

	public void setImporteurTxt(String importeurTxt) {
		this.importeurTxt = importeurTxt;
	}

	@Column(name = "PI_MITTELNAME", length = 110)
	public String getPiMittelname() {
		return this.piMittelname;
	}

	public void setPiMittelname(String piMittelname) {
		this.piMittelname = piMittelname;
	}

	@Column(name = "GUELTIG", length = 7)
	public Date getGueltig() {
		return this.gueltig;
	}

	public void setGueltig(Date gueltig) {
		this.gueltig = gueltig;
	}

	@Column(name = "PI_BESCHEIDNR", length = 2)
	public String getPiBescheidnr() {
		return this.piBescheidnr;
	}

	public void setPiBescheidnr(String piBescheidnr) {
		this.piBescheidnr = piBescheidnr;
	}

	@Column(name = "BESCHEID_DATUM", length = 7)
	public Date getBescheidDatum() {
		return this.bescheidDatum;
	}

	public void setBescheidDatum(Date bescheidDatum) {
		this.bescheidDatum = bescheidDatum;
	}

	@Convert(converter = BooleanToStringConverter.class)
	@Column(name = "BESCHEINIGUNG", length = 1)
	public Boolean getBescheinigung() {
		return this.bescheinigung;
	}

	@Convert(converter = BooleanToStringConverter.class)
	public void setBescheinigung(Boolean bescheinigung) {
		this.bescheinigung = bescheinigung;
	}

	@Column(name = "MITTELNAME", length = 110)
	public String getMittelname() {
		return this.mittelname;
	}

	public void setMittelname(String mittelname) {
		this.mittelname = mittelname;
	}

	@Column(name = "IMPORTEUR_NR", precision = 22, scale = 0)
	public BigDecimal getImporteurNr() {
		return this.importeurNr;
	}

	public void setImporteurNr(BigDecimal importeurNr) {
		this.importeurNr = importeurNr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ParallelimportGueltigId))
			return false;
		ParallelimportGueltigId castOther = (ParallelimportGueltigId) other;

		return ((this.getPiPsmnr() == castOther.getPiPsmnr()) || (this.getPiPsmnr() != null
						&& castOther.getPiPsmnr() != null && this.getPiPsmnr().equals(castOther.getPiPsmnr())))
				&& ((this.getPiReferenzKennr() == castOther.getPiReferenzKennr())
						|| (this.getPiReferenzKennr() != null && castOther.getPiReferenzKennr() != null
								&& this.getPiReferenzKennr().equals(castOther.getPiReferenzKennr())))
				&& ((this.getPiKennziffer() == castOther.getPiKennziffer())
						|| (this.getPiKennziffer() != null && castOther.getPiKennziffer() != null
								&& this.getPiKennziffer().equals(castOther.getPiKennziffer())))
				&& ((this.getPiStatus() == castOther.getPiStatus()) || (this.getPiStatus() != null
						&& castOther.getPiStatus() != null && this.getPiStatus().equals(castOther.getPiStatus())))
				&& ((this.getImporteurTxt() == castOther.getImporteurTxt())
						|| (this.getImporteurTxt() != null && castOther.getImporteurTxt() != null
								&& this.getImporteurTxt().equals(castOther.getImporteurTxt())))
				&& ((this.getPiMittelname() == castOther.getPiMittelname())
						|| (this.getPiMittelname() != null && castOther.getPiMittelname() != null
								&& this.getPiMittelname().equals(castOther.getPiMittelname())))
				&& ((this.getGueltig() == castOther.getGueltig()) || (this.getGueltig() != null
						&& castOther.getGueltig() != null && this.getGueltig().equals(castOther.getGueltig())))
				&& ((this.getPiBescheidnr() == castOther.getPiBescheidnr())
						|| (this.getPiBescheidnr() != null && castOther.getPiBescheidnr() != null
								&& this.getPiBescheidnr().equals(castOther.getPiBescheidnr())))
				&& ((this.getBescheidDatum() == castOther.getBescheidDatum())
						|| (this.getBescheidDatum() != null && castOther.getBescheidDatum() != null
								&& this.getBescheidDatum().equals(castOther.getBescheidDatum())))
				&& ((this.getBescheinigung() == castOther.getBescheinigung())
						|| (this.getBescheinigung() != null && castOther.getBescheinigung() != null
								&& this.getBescheinigung().equals(castOther.getBescheinigung())))
				&& ((this.getMittelname() == castOther.getMittelname()) || (this.getMittelname() != null
						&& castOther.getMittelname() != null && this.getMittelname().equals(castOther.getMittelname())))
				&& ((this.getImporteurNr() == castOther.getImporteurNr())
						|| (this.getImporteurNr() != null && castOther.getImporteurNr() != null
								&& this.getImporteurNr().equals(castOther.getImporteurNr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPiPsmnr() == null ? 0 : this.getPiPsmnr().hashCode());
		result = 37 * result + (getPiReferenzKennr() == null ? 0 : this.getPiReferenzKennr().hashCode());
		result = 37 * result + (getPiKennziffer() == null ? 0 : this.getPiKennziffer().hashCode());
		result = 37 * result + (getPiStatus() == null ? 0 : this.getPiStatus().hashCode());
		result = 37 * result + (getImporteurTxt() == null ? 0 : this.getImporteurTxt().hashCode());
		result = 37 * result + (getPiMittelname() == null ? 0 : this.getPiMittelname().hashCode());
		result = 37 * result + (getGueltig() == null ? 0 : this.getGueltig().hashCode());
		result = 37 * result + (getPiBescheidnr() == null ? 0 : this.getPiBescheidnr().hashCode());
		result = 37 * result + (getBescheidDatum() == null ? 0 : this.getBescheidDatum().hashCode());
		result = 37 * result + (getBescheinigung() == null ? 0 : this.getBescheinigung().hashCode());
		result = 37 * result + (getMittelname() == null ? 0 : this.getMittelname().hashCode());
		result = 37 * result + (getImporteurNr() == null ? 0 : this.getImporteurNr().hashCode());
		return result;
	}

}
