package de.dredlich.psm.api.datenschubser.model.pk;

import java.math.BigDecimal;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * StaerkungVertriebId generated by hbm2java
 */
@Embeddable
public class StaerkungVertriebId implements java.io.Serializable, ICompPK {

	private String kennr;
	private String vertriebsfirma;
	private BigDecimal vertriebsfirmaNr;

	public StaerkungVertriebId() {
	}

	public StaerkungVertriebId(String kennr, String vertriebsfirma, BigDecimal vertriebsfirmaNr) {
		this.kennr = kennr;
		this.vertriebsfirma = vertriebsfirma;
		this.vertriebsfirmaNr = vertriebsfirmaNr;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "VERTRIEBSFIRMA", length = 20)
	public String getVertriebsfirma() {
		return this.vertriebsfirma;
	}

	public void setVertriebsfirma(String vertriebsfirma) {
		this.vertriebsfirma = vertriebsfirma;
	}

	@Column(name = "VERTRIEBSFIRMA_NR", nullable = false, precision = 22, scale = 0)
	public BigDecimal getVertriebsfirmaNr() {
		return this.vertriebsfirmaNr;
	}

	public void setVertriebsfirmaNr(BigDecimal vertriebsfirmaNr) {
		this.vertriebsfirmaNr = vertriebsfirmaNr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StaerkungVertriebId))
			return false;
		StaerkungVertriebId castOther = (StaerkungVertriebId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null
						&& castOther.getKennr() != null && this.getKennr().equals(castOther.getKennr())))
				&& ((this.getVertriebsfirma() == castOther.getVertriebsfirma())
						|| (this.getVertriebsfirma() != null && castOther.getVertriebsfirma() != null
								&& this.getVertriebsfirma().equals(castOther.getVertriebsfirma())))
				&& ((this.getVertriebsfirmaNr() == castOther.getVertriebsfirmaNr())
						|| (this.getVertriebsfirmaNr() != null && castOther.getVertriebsfirmaNr() != null
								&& this.getVertriebsfirmaNr().equals(castOther.getVertriebsfirmaNr())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getVertriebsfirma() == null ? 0 : this.getVertriebsfirma().hashCode());
		result = 37 * result + (getVertriebsfirmaNr() == null ? 0 : this.getVertriebsfirmaNr().hashCode());
		return result;
	}

}
