package de.dredlich.psm.api.datenschubser.model.pk;

import java.util.Date;
import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * StandId generated by hbm2java
 */
@Embeddable
public class StandId implements java.io.Serializable, ICompPK {

	private Date datum;

	public StandId() {
	}

	public StandId(Date datum) {
		this.datum = datum;
	}

	public StandId(String MRow$$, Date datum) {
		this.datum = datum;
	}

	@Column(name = "DATUM", nullable = false, length = 7)
	public Date getDatum() {
		return this.datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof StandId))
			return false;
		StandId castOther = (StandId) other;

		return ((this.getDatum() == castOther.getDatum()) || (this.getDatum() != null
						&& castOther.getDatum() != null && this.getDatum().equals(castOther.getDatum())));
	}

	public int hashCode() {
		int result = 17;
		result = 37 * result + (getDatum() == null ? 0 : this.getDatum().hashCode());
		return result;
	}

}
