package de.dredlich.psm.api.datenschubser.model.pk;

import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

import java.math.BigDecimal;

/**
 * ZusatzstoffVertriebId generated by hbm2java
 */
@Embeddable
public class ZusatzstoffVertriebId implements java.io.Serializable, ICompPK {

	private String kennr;
	private BigDecimal vertriebsfirmaNr;

	public ZusatzstoffVertriebId() {
	}

	public ZusatzstoffVertriebId(String kennr, BigDecimal vertriebsfirmaNr) {
		this.kennr = kennr;
		this.vertriebsfirmaNr = vertriebsfirmaNr;
	}

	@Column(name = "KENNR", nullable = false, length = 9)
	public String getKennr() {
		return this.kennr;
	}

	public void setKennr(String kennr) {
		this.kennr = kennr;
	}

	@Column(name = "VERTRIEBSFIRMA_NR", nullable = false, precision = 22)
	public BigDecimal getVertriebsfirmaNr() {
		return this.vertriebsfirmaNr;
	}

	public void setVertriebsfirmaNr(BigDecimal vertriebsfirmaNr) {
		this.vertriebsfirmaNr = vertriebsfirmaNr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ZusatzstoffVertriebId))
			return false;
		ZusatzstoffVertriebId castOther = (ZusatzstoffVertriebId) other;

		return ((this.getKennr() == castOther.getKennr()) || (this.getKennr() != null
						&& castOther.getKennr() != null && this.getKennr().equals(castOther.getKennr())))
				&& ((this.getVertriebsfirmaNr() == castOther.getVertriebsfirmaNr())
						|| (this.getVertriebsfirmaNr() != null && castOther.getVertriebsfirmaNr() != null
								&& this.getVertriebsfirmaNr().equals(castOther.getVertriebsfirmaNr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getKennr() == null ? 0 : this.getKennr().hashCode());
		result = 37 * result + (getVertriebsfirmaNr() == null ? 0 : this.getVertriebsfirmaNr().hashCode());
		return result;
	}


}
