/*
 * Java domain class for entity "AuflageRedu"
 * Created on 2020-10-04 ( Date ISO 2020-10-04 - Time 20:42:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package de.dredlich.psm.api.datenschubser.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;

/**
 * Domain class for entity "AuflageRedu"
 *
 * @author Telosys Tools Generator
 *
 */

@JsonIgnoreProperties(ignoreUnknown = true)
public class AuflageRedu implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------

	@JsonProperty("kategorie")
    private String     kategorie    ;

	@JsonProperty("redu_abstand")
    private String     reduAbstand  ;

	@JsonProperty("auflagenr")
	private Long auflagenr    ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AuflageRedu() {
		super();
    }

    public void setKategorie( String kategorie ) {
        this.kategorie = kategorie ;
    }
    public String getKategorie() {
        return this.kategorie;
    }

    public void setReduAbstand( String reduAbstand ) {
        this.reduAbstand = reduAbstand ;
    }
    public String getReduAbstand() {
        return this.reduAbstand;
    }


//    //----------------------------------------------------------------------
//    // toString METHOD
//    //----------------------------------------------------------------------
//    public String toString() {
//        StringBuffer sb = new StringBuffer();
//        //sb.append(mRow$$);
//        sb.append("|");
//        sb.append(kategorie);
//        sb.append("|");
//        sb.append(reduAbstand);
//        sb.append("|");
//        sb.append(auflagenr);
//        return sb.toString();
//    }

}
