/*
 * Java domain class for entity "AwgBem"
 * Created on 2020-10-04 ( Date ISO 2020-10-04 - Time 20:42:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package de.dredlich.psm.api.datenschubser.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;


/**
 * Domain class for entity "AwgBem"
 *
 * @author Telosys Tools Generator
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class AwgBem implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY
    //----------------------------------------------------------------------
	@JsonProperty("awg_id")
    private String     awgId        ;
	@JsonProperty("auflage_bem")
    private String     auflageBem   ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------

	@JsonProperty("auflage_bereich")
    private String     auflageBereich ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public AwgBem() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setAwgId( String awgId ) {
        this.awgId = awgId ;
    }
    public String getAwgId() {
        return this.awgId;
    }

    public void setAuflageBem( String auflageBem ) {
        this.auflageBem = auflageBem ;
    }
    public String getAuflageBem() {
        return this.auflageBem;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------

    public void setAuflageBereich( String auflageBereich ) {
        this.auflageBereich = auflageBereich ;
    }
    public String getAuflageBereich() {
        return this.auflageBereich;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(awgId);
        sb.append("|");
        sb.append(auflageBem);
        sb.append("|");
        sb.append(auflageBereich);
        return sb.toString();
    }

}
