/*
 * Java domain class for entity "KodelisteFeldname"
 * Created on 2020-10-04 ( Date ISO 2020-10-04 - Time 20:42:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package de.dredlich.psm.api.datenschubser.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;


/**
 * Domain class for entity "KodelisteFeldname"
 *
 * @author Telosys Tools Generator
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class KodelisteFeldname implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY
    //----------------------------------------------------------------------
	@JsonProperty("tabelle")
    private String     tabelle      ;
	@JsonProperty("kodeliste")
    private Integer    kodeliste    ;
	@JsonProperty("feldname")
    private String     feldname     ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public KodelisteFeldname() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setTabelle( String tabelle ) {
        this.tabelle = tabelle ;
    }
    public String getTabelle() {
        return this.tabelle;
    }

    public void setKodeliste( Integer kodeliste ) {
        this.kodeliste = kodeliste ;
    }
    public Integer getKodeliste() {
        return this.kodeliste;
    }

    public void setFeldname( String feldname ) {
        this.feldname = feldname ;
    }
    public String getFeldname() {
        return this.feldname;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(tabelle);
        sb.append("|");
        sb.append(kodeliste);
        sb.append("|");
        sb.append(feldname);
        return sb.toString();
    }

}
