/*
 * Java domain class for entity "KulturGruppe"
 * Created on 2020-10-04 ( Date ISO 2020-10-04 - Time 20:42:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package de.dredlich.psm.api.datenschubser.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;


/**
 * Domain class for entity "KulturGruppe"
 *
 * @author Telosys Tools Generator
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class KulturGruppe implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY
    //----------------------------------------------------------------------
	@JsonProperty("kultur_gruppe")
    private String     kulturGruppe ;
	@JsonProperty("kultur")
    private String     kultur       ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public KulturGruppe() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setKulturGruppe( String kulturGruppe ) {
        this.kulturGruppe = kulturGruppe ;
    }
    public String getKulturGruppe() {
        return this.kulturGruppe;
    }

    public void setKultur( String kultur ) {
        this.kultur = kultur ;
    }
    public String getKultur() {
        return this.kultur;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(kulturGruppe);
        sb.append("|");
        sb.append(kultur);
        return sb.toString();
    }

}
