/*
 * Java domain class for entity "MittelVertrieb"
 * Created on 2020-10-04 ( Date ISO 2020-10-04 - Time 20:42:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package de.dredlich.psm.api.datenschubser.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.math.BigDecimal;

/**
 * Domain class for entity "MittelVertrieb"
 *
 * @author Telosys Tools Generator
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class MittelVertrieb implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY
    //----------------------------------------------------------------------
	@JsonProperty("kennr")
    private String     kennr        ;
	@JsonProperty("vertriebsfirma_nr")
    private BigDecimal vertriebsfirmaNr ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
	@JsonProperty("vertriebsfirma")
    private String     vertriebsfirma ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MittelVertrieb() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setKennr( String kennr ) {
        this.kennr = kennr ;
    }
    public String getKennr() {
        return this.kennr;
    }

    public void setVertriebsfirmaNr( BigDecimal vertriebsfirmaNr ) {
        this.vertriebsfirmaNr = vertriebsfirmaNr ;
    }
    public BigDecimal getVertriebsfirmaNr() {
        return this.vertriebsfirmaNr;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------
    public void setVertriebsfirma( String vertriebsfirma ) {
        this.vertriebsfirma = vertriebsfirma ;
    }
    public String getVertriebsfirma() {
        return this.vertriebsfirma;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(kennr);
        sb.append("|");
        sb.append(vertriebsfirmaNr);
        sb.append("|");
        sb.append(vertriebsfirma);
        return sb.toString();
    }

}
