/*
 * Java domain class for entity "MittelWirkbereich"
 * Created on 2020-10-04 ( Date ISO 2020-10-04 - Time 20:42:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package de.dredlich.psm.api.datenschubser.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;


/**
 * Domain class for entity "MittelWirkbereich"
 *
 * @author Telosys Tools Generator
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class MittelWirkbereich implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY
    //----------------------------------------------------------------------
	@JsonProperty("kennr")
    private String     kennr        ;
	@JsonProperty("wirkungsbereich")
    private String     wirkungsbereich ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public MittelWirkbereich() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setKennr( String kennr ) {
        this.kennr = kennr ;
    }
    public String getKennr() {
        return this.kennr;
    }

    public void setWirkungsbereich( String wirkungsbereich ) {
        this.wirkungsbereich = wirkungsbereich ;
    }
    public String getWirkungsbereich() {
        return this.wirkungsbereich;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(kennr);
        sb.append("|");
        sb.append(wirkungsbereich);
        return sb.toString();
    }

}
