/*
 * Java domain class for entity "SchadorgGruppe"
 * Created on 2020-10-04 ( Date ISO 2020-10-04 - Time 20:42:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package de.dredlich.psm.api.datenschubser.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;


/**
 * Domain class for entity "SchadorgGruppe"
 *
 * @author Telosys Tools Generator
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class SchadorgGruppe implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY
    //----------------------------------------------------------------------
	@JsonProperty("schadorg")
    private String     schadorg     ;
	@JsonProperty("schadorg_gruppe")
    private String     schadorgGruppe ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public SchadorgGruppe() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setSchadorg( String schadorg ) {
        this.schadorg = schadorg ;
    }
    public String getSchadorg() {
        return this.schadorg;
    }

    public void setSchadorgGruppe( String schadorgGruppe ) {
        this.schadorgGruppe = schadorgGruppe ;
    }
    public String getSchadorgGruppe() {
        return this.schadorgGruppe;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(schadorg);
        sb.append("|");
        sb.append(schadorgGruppe);
        return sb.toString();
    }

}
