/*
 * Java domain class for entity "Staerkung"
 * Created on 2020-10-04 ( Date ISO 2020-10-04 - Time 20:42:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package de.dredlich.psm.api.datenschubser.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Domain class for entity "Staerkung"
 *
 * @author Telosys Tools Generator
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Staerkung implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY
    //----------------------------------------------------------------------
	@JsonProperty("kennr")
    private String     kennr        ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
	@JsonProperty("genehmigung_am")
    private Date       genehmigungAm ;

	@JsonProperty("mittelname")
    private String     mittelname   ;

	@JsonProperty("antragsteller")
    private String     antragsteller ;

	@JsonProperty("antragsteller_nr")
    private BigDecimal antragstellerNr ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Staerkung() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setKennr( String kennr ) {
        this.kennr = kennr ;
    }
    public String getKennr() {
        return this.kennr;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------

    public void setGenehmigungAm( Date genehmigungAm ) {
        this.genehmigungAm = genehmigungAm ;
    }
    public Date getGenehmigungAm() {
        return this.genehmigungAm;
    }

    public void setMittelname( String mittelname ) {
        this.mittelname = mittelname ;
    }
    public String getMittelname() {
        return this.mittelname;
    }

    public void setAntragsteller( String antragsteller ) {
        this.antragsteller = antragsteller ;
    }
    public String getAntragsteller() {
        return this.antragsteller;
    }

    public void setAntragstellerNr( BigDecimal antragstellerNr ) {
        this.antragstellerNr = antragstellerNr ;
    }
    public BigDecimal getAntragstellerNr() {
        return this.antragstellerNr;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(kennr);
        sb.append("|");
        sb.append(genehmigungAm);
        sb.append("|");
        sb.append(mittelname);
        sb.append("|");
        sb.append(antragsteller);
        sb.append("|");
        sb.append(antragstellerNr);
        return sb.toString();
    }

}
