/*
 * Java domain class for entity "Wirkstoff"
 * Created on 2020-10-04 ( Date ISO 2020-10-04 - Time 20:42:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package de.dredlich.psm.api.datenschubser.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

import java.io.Serializable;


/**
 * Domain class for entity "Wirkstoff"
 *
 * @author Telosys Tools Generator
 *
 */
@JsonIgnoreProperties(ignoreUnknown = true)
public class Wirkstoff implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY
    //----------------------------------------------------------------------
	@JsonProperty("wirknr")
    private String     wirknr       ;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    //----------------------------------------------------------------------
	@JsonProperty("wirkstoffname")
    private String     wirkstoffname ;

	@JsonProperty("wirkstoffname_en")
    private String     wirkstoffnameEn ;

	@JsonProperty("kategorie")
    private String     kategorie    ;

	@JsonProperty("genehmigt")
    private String     genehmigt    ;

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Wirkstoff() {
		super();
    }

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR "KEY FIELD(S)"
    //----------------------------------------------------------------------
    public void setWirknr( String wirknr ) {
        this.wirknr = wirknr ;
    }
    public String getWirknr() {
        return this.wirknr;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR "DATA FIELDS"
    //----------------------------------------------------------------------

    public void setWirkstoffname( String wirkstoffname ) {
        this.wirkstoffname = wirkstoffname ;
    }
    public String getWirkstoffname() {
        return this.wirkstoffname;
    }

    public void setWirkstoffnameEn( String wirkstoffnameEn ) {
        this.wirkstoffnameEn = wirkstoffnameEn ;
    }
    public String getWirkstoffnameEn() {
        return this.wirkstoffnameEn;
    }

    public void setKategorie( String kategorie ) {
        this.kategorie = kategorie ;
    }
    public String getKategorie() {
        return this.kategorie;
    }

    public void setGenehmigt( String genehmigt ) {
        this.genehmigt = genehmigt ;
    }
    public String getGenehmigt() {
        return this.genehmigt;
    }

    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
        StringBuffer sb = new StringBuffer();
        sb.append(wirknr);
        sb.append("|");
        sb.append(wirkstoffname);
        sb.append("|");
        sb.append(wirkstoffnameEn);
        sb.append("|");
        sb.append(kategorie);
        sb.append("|");
        sb.append(genehmigt);
        return sb.toString();
    }

}
