package de.dredlich.psm.api.datenschubser.model.awg;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import de.dredlich.psm.api.datenschubser.converter.BooleanToStringConverter;
import de.dredlich.psm.api.datenschubser.model.ISetItem;
import jakarta.persistence.*;

import java.math.BigDecimal;

/**
 * Awg generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "AWG", uniqueConstraints = {@UniqueConstraint(columnNames = {"KENNR", "ANTRAGNR", "AWGNR"})})
public class Awg implements ISetItem {

    private String awgId;
    private String kennr;
    private String antragnr;
    private String awgnr;
    private BigDecimal anwendungenAnzJeBefall;
    private BigDecimal anwendungenMaxJeKultur;
    private BigDecimal anwendungenMaxJeVegetation;
    private String anwendungsbereich;
    private String anwendungstechnik;
    private BigDecimal awAbstandBis;
    private String awAbstandEinheit;
    private BigDecimal awAbstandVon;
    private String einsatzgebiet;
    private String kulturErl;
    private String schadorgErl;
    private String stadiumKulturBem;
    private String stadiumKulturBis;
    private Short stadiumKulturKodeliste;
    private String stadiumKulturVon;
    private String stadiumSchadorgBem;
    private String stadiumSchadorgBis;
    private Short stadiumSchadorgKodeliste;
    private String stadiumSchadorgVon;
    private String wirkungsbereich;
    private Boolean genehmigung;
    private Boolean huk;

    public Awg() {
    }

    public Awg(String awgId,
               String kennr,
               String antragnr,
               String awgnr,
               BigDecimal anwendungenAnzJeBefall,
               BigDecimal anwendungenMaxJeKultur,
               BigDecimal anwendungenMaxJeVegetation,
               String anwendungsbereich,
               String anwendungstechnik,
               BigDecimal awAbstandBis,
               String awAbstandEinheit,
               BigDecimal awAbstandVon,
               String einsatzgebiet,
               String kulturErl,
               String schadorgErl,
               String stadiumKulturBem,
               String stadiumKulturBis,
               Short stadiumKulturKodeliste,
               String stadiumKulturVon,
               String stadiumSchadorgBem,
               String stadiumSchadorgBis,
               Short stadiumSchadorgKodeliste,
               String stadiumSchadorgVon,
               String wirkungsbereich,
               Boolean genehmigung,
               Boolean huk) {
        this.awgId = awgId;
        this.kennr = kennr;
        this.antragnr = antragnr;
        this.awgnr = awgnr;
        this.anwendungenAnzJeBefall = anwendungenAnzJeBefall;
        this.anwendungenMaxJeKultur = anwendungenMaxJeKultur;
        this.anwendungenMaxJeVegetation = anwendungenMaxJeVegetation;
        this.anwendungsbereich = anwendungsbereich;
        this.anwendungstechnik = anwendungstechnik;
        this.awAbstandBis = awAbstandBis;
        this.awAbstandEinheit = awAbstandEinheit;
        this.awAbstandVon = awAbstandVon;
        this.einsatzgebiet = einsatzgebiet;
        this.kulturErl = kulturErl;
        this.schadorgErl = schadorgErl;
        this.stadiumKulturBem = stadiumKulturBem;
        this.stadiumKulturBis = stadiumKulturBis;
        this.stadiumKulturKodeliste = stadiumKulturKodeliste;
        this.stadiumKulturVon = stadiumKulturVon;
        this.stadiumSchadorgBem = stadiumSchadorgBem;
        this.stadiumSchadorgBis = stadiumSchadorgBis;
        this.stadiumSchadorgKodeliste = stadiumSchadorgKodeliste;
        this.stadiumSchadorgVon = stadiumSchadorgVon;
        this.wirkungsbereich = wirkungsbereich;
        this.genehmigung = genehmigung;
        this.huk = huk;
    }

    @Id
    @Column(name = "AWG_ID", unique = true, nullable = false, length = 16)
    public String getAwgId() {
        return this.awgId;
    }

    public void setAwgId(String awgId) {
        this.awgId = awgId;
    }

    @Column(name = "AWGNR", length = 3)
    public String getAwgnr() {
        return this.awgnr;
    }

    public void setAwgnr(String awgnr) {
        this.awgnr = awgnr;
    }

    @Column(name = "KENNR", length = 9)
    public String getKennr() {
        return this.kennr;
    }

    public void setKennr(String kennr) {
        this.kennr = kennr;
    }

    @Column(name = "ANTRAGNR", length = 2)
    public String getAntragnr() {
        return this.antragnr;
    }

    public void setAntragnr(String antragnr) {
        this.antragnr = antragnr;
    }

    @Column(name = "ANWENDUNGEN_ANZ_JE_BEFALL", precision = 22, scale = 0)
    public BigDecimal getAnwendungenAnzJeBefall() {
        return this.anwendungenAnzJeBefall;
    }

    public void setAnwendungenAnzJeBefall(BigDecimal anwendungenAnzJeBefall) {
        this.anwendungenAnzJeBefall = anwendungenAnzJeBefall;
    }

    @Column(name = "ANWENDUNGEN_MAX_JE_KULTUR", precision = 22, scale = 0)
    public BigDecimal getAnwendungenMaxJeKultur() {
        return this.anwendungenMaxJeKultur;
    }

    public void setAnwendungenMaxJeKultur(BigDecimal anwendungenMaxJeKultur) {
        this.anwendungenMaxJeKultur = anwendungenMaxJeKultur;
    }

    @Column(name = "ANWENDUNGEN_MAX_JE_VEGETATION", precision = 22, scale = 0)
    public BigDecimal getAnwendungenMaxJeVegetation() {
        return this.anwendungenMaxJeVegetation;
    }

    public void setAnwendungenMaxJeVegetation(BigDecimal anwendungenMaxJeVegetation) {
        this.anwendungenMaxJeVegetation = anwendungenMaxJeVegetation;
    }

    @Column(name = "ANWENDUNGSBEREICH", length = 20)
    public String getAnwendungsbereich() {
        return this.anwendungsbereich;
    }

    public void setAnwendungsbereich(String anwendungsbereich) {
        this.anwendungsbereich = anwendungsbereich;
    }

    @Column(name = "ANWENDUNGSTECHNIK", length = 20)
    public String getAnwendungstechnik() {
        return this.anwendungstechnik;
    }

    public void setAnwendungstechnik(String anwendungstechnik) {
        this.anwendungstechnik = anwendungstechnik;
    }

    @Column(name = "AW_ABSTAND_BIS", precision = 22, scale = 0)
    public BigDecimal getAwAbstandBis() {
        return this.awAbstandBis;
    }

    public void setAwAbstandBis(BigDecimal awAbstandBis) {
        this.awAbstandBis = awAbstandBis;
    }

    @Column(name = "AW_ABSTAND_EINHEIT", length = 20)
    public String getAwAbstandEinheit() {
        return this.awAbstandEinheit;
    }

    public void setAwAbstandEinheit(String awAbstandEinheit) {
        this.awAbstandEinheit = awAbstandEinheit;
    }

    @Column(name = "AW_ABSTAND_VON", precision = 22, scale = 0)
    public BigDecimal getAwAbstandVon() {
        return this.awAbstandVon;
    }

    public void setAwAbstandVon(BigDecimal awAbstandVon) {
        this.awAbstandVon = awAbstandVon;
    }

    @Column(name = "EINSATZGEBIET", length = 20)
    public String getEinsatzgebiet() {
        return this.einsatzgebiet;
    }

    public void setEinsatzgebiet(String einsatzgebiet) {
        this.einsatzgebiet = einsatzgebiet;
    }

    @Column(name = "KULTUR_ERL", length = 20)
    public String getKulturErl() {
        return this.kulturErl;
    }

    public void setKulturErl(String kulturErl) {
        this.kulturErl = kulturErl;
    }

    @Column(name = "SCHADORG_ERL", length = 20)
    public String getSchadorgErl() {
        return this.schadorgErl;
    }

    public void setSchadorgErl(String schadorgErl) {
        this.schadorgErl = schadorgErl;
    }

    @Column(name = "STADIUM_KULTUR_BEM", length = 2000)
    public String getStadiumKulturBem() {
        return this.stadiumKulturBem;
    }

    public void setStadiumKulturBem(String stadiumKulturBem) {
        this.stadiumKulturBem = stadiumKulturBem;
    }

    @Column(name = "STADIUM_KULTUR_BIS", length = 20)
    public String getStadiumKulturBis() {
        return this.stadiumKulturBis;
    }

    public void setStadiumKulturBis(String stadiumKulturBis) {
        this.stadiumKulturBis = stadiumKulturBis;
    }

    @Column(name = "STADIUM_KULTUR_KODELISTE", precision = 3, scale = 0)
    public Short getStadiumKulturKodeliste() {
        return this.stadiumKulturKodeliste;
    }

    public void setStadiumKulturKodeliste(Short stadiumKulturKodeliste) {
        this.stadiumKulturKodeliste = stadiumKulturKodeliste;
    }

    @Column(name = "STADIUM_KULTUR_VON", length = 20)
    public String getStadiumKulturVon() {
        return this.stadiumKulturVon;
    }

    public void setStadiumKulturVon(String stadiumKulturVon) {
        this.stadiumKulturVon = stadiumKulturVon;
    }

    @Column(name = "STADIUM_SCHADORG_BEM", length = 2000)
    public String getStadiumSchadorgBem() {
        return this.stadiumSchadorgBem;
    }

    public void setStadiumSchadorgBem(String stadiumSchadorgBem) {
        this.stadiumSchadorgBem = stadiumSchadorgBem;
    }

    @Column(name = "STADIUM_SCHADORG_BIS", length = 20)
    public String getStadiumSchadorgBis() {
        return this.stadiumSchadorgBis;
    }

    public void setStadiumSchadorgBis(String stadiumSchadorgBis) {
        this.stadiumSchadorgBis = stadiumSchadorgBis;
    }

    @Column(name = "STADIUM_SCHADORG_KODELISTE", precision = 3, scale = 0)
    public Short getStadiumSchadorgKodeliste() {
        return this.stadiumSchadorgKodeliste;
    }

    public void setStadiumSchadorgKodeliste(Short stadiumSchadorgKodeliste) {
        this.stadiumSchadorgKodeliste = stadiumSchadorgKodeliste;
    }

    @Column(name = "STADIUM_SCHADORG_VON", length = 20)
    public String getStadiumSchadorgVon() {
        return this.stadiumSchadorgVon;
    }

    public void setStadiumSchadorgVon(String stadiumSchadorgVon) {
        this.stadiumSchadorgVon = stadiumSchadorgVon;
    }

    @Column(name = "WIRKUNGSBEREICH", length = 20)
    public String getWirkungsbereich() {
        return this.wirkungsbereich;
    }

    public void setWirkungsbereich(String wirkungsbereich) {
        this.wirkungsbereich = wirkungsbereich;
    }

    @Convert(converter = BooleanToStringConverter.class)
    @Column(name = "GENEHMIGUNG", length = 1)
    public Boolean getGenehmigung() {
        return this.genehmigung;
    }

    @Convert(converter = BooleanToStringConverter.class)
    public void setGenehmigung(Boolean genehmigung) {
        this.genehmigung = genehmigung;
    }

    @Convert(converter = BooleanToStringConverter.class)
    @Column(name = "HUK", length = 1)
    public Boolean getHuk() {
        return this.huk;
    }

    @Convert(converter = BooleanToStringConverter.class)
    public void setHuk(Boolean huk) {
        this.huk = huk;
    }

}
