package de.dredlich.psm.api.datenschubser.model.awg;

import de.dredlich.psm.api.datenschubser.model.pk.AwgAufwandId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

import java.math.BigDecimal;

/**
 * AwgAufwand generated by hbm2java
 */
@Entity
@Table(name = "AWG_AUFWAND")
public class AwgAufwand implements java.io.Serializable, ISetItemPK {

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "awgId", column = @Column(name = "AWG_ID", nullable = false, length = 16)),
			@AttributeOverride(name = "aufwandbedingung", column = @Column(name = "AUFWANDBEDINGUNG", nullable = false, length = 20)),
			@AttributeOverride(name = "sortierNr", column = @Column(name = "SORTIER_NR", nullable = false, precision = 22)) })
	private AwgAufwandId id;

	@Column(name = "M_AUFWAND", precision = 10, scale = 4)
	private BigDecimal MAufwand;

	@Column(name = "M_AUFWAND_EINHEIT", length = 20)
	private String MAufwandEinheit;

	@Column(name = "W_AUFWAND_VON", precision = 14, scale = 4)
	private BigDecimal WAufwandVon;

	@Column(name = "W_AUFWAND_BIS", precision = 14, scale = 4)
	private BigDecimal WAufwandBis;

	@Column(name = "W_AUFWAND_EINHEIT", length = 20)
	private String WAufwandEinheit;

	public AwgAufwand() {
	}

	public AwgAufwand(AwgAufwandId id, BigDecimal MAufwand, String MAufwandEinheit, BigDecimal WAufwandVon, BigDecimal WAufwandBis, String WAufwandEinheit) {
		this.id = id;
		this.MAufwand = MAufwand;
		this.MAufwandEinheit = MAufwandEinheit;
		this.WAufwandVon = WAufwandVon;
		this.WAufwandBis = WAufwandBis;
		this.WAufwandEinheit = WAufwandEinheit;
	}

	public AwgAufwandId getId() {
		return this.id;
	}

	public void setId(AwgAufwandId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (AwgAufwandId) id;
	}

	public BigDecimal getMAufwand() {
		return MAufwand;
	}

	public void setMAufwand(BigDecimal MAufwand) {
		this.MAufwand = MAufwand;
	}

	public String getMAufwandEinheit() {
		return MAufwandEinheit;
	}

	public void setMAufwandEinheit(String MAufwandEinheit) {
		this.MAufwandEinheit = MAufwandEinheit;
	}

	public BigDecimal getWAufwandVon() {
		return WAufwandVon;
	}

	public void setWAufwandVon(BigDecimal WAufwandVon) {
		this.WAufwandVon = WAufwandVon;
	}

	public BigDecimal getWAufwandBis() {
		return WAufwandBis;
	}

	public void setWAufwandBis(BigDecimal WAufwandBis) {
		this.WAufwandBis = WAufwandBis;
	}

	public String getWAufwandEinheit() {
		return WAufwandEinheit;
	}

	public void setWAufwandEinheit(String WAufwandEinheit) {
		this.WAufwandEinheit = WAufwandEinheit;
	}
}
