package de.dredlich.psm.api.datenschubser.model.awg;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import de.dredlich.psm.api.datenschubser.model.pk.AwgBemId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * AwgBem generated by hbm2java
 */
@Entity
@Table(name = "AWG_BEM")
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
public class AwgBem implements java.io.Serializable, ISetItemPK {

	private AwgBemId id;
	private String auflageBereich;

	public AwgBem() {}

	public AwgBem(AwgBemId id, String auflageBereich) {
		this.id = id;
		this.auflageBereich = auflageBereich;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "awgId", column = @Column(name = "AWG_ID", nullable = false, length = 16)),
			@AttributeOverride(name = "auflageBem", column = @Column(name = "AUFLAGE_BEM", nullable = false, length = 20)) })
	public AwgBemId getId() {
		return this.id;
	}

	public void setId(AwgBemId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (AwgBemId) id;
	}

	@Column(name = "AUFLAGE_BEREICH", length = 2)
	public String getAuflageBereich() {
		return this.auflageBereich;
	}

	public void setAuflageBereich(String auflageBereich) {
		this.auflageBereich = auflageBereich;
	}

}
