package de.dredlich.psm.api.datenschubser.model.awg;

import de.dredlich.psm.api.datenschubser.converter.BooleanToStringConverter;
import de.dredlich.psm.api.datenschubser.model.pk.AwgKulturId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

import java.math.BigDecimal;

/**
 * AwgKultur generated by hbm2java
 */
@Entity
@Table(name = "AWG_KULTUR")
public class AwgKultur implements java.io.Serializable, ISetItemPK {

	private AwgKulturId id;
	private Boolean ausgenommen;
	private BigDecimal sortierNr;

	public AwgKultur() {
	}

	public AwgKultur(AwgKulturId id, Boolean ausgenommen, BigDecimal sortierNr) {
		this.id = id;
		this.ausgenommen = ausgenommen;
		this.sortierNr = sortierNr;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "awgId", column = @Column(name = "AWG_ID", nullable = false, length = 16)),
			@AttributeOverride(name = "kultur", column = @Column(name = "KULTUR", nullable = false, length = 20)) })
	public AwgKulturId getId() {
		return this.id;
	}

	public void setId(AwgKulturId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (AwgKulturId) id;
	}

	@Convert(converter = BooleanToStringConverter.class)
	@Column(name = "AUSGENOMMEN", length = 1)
	public Boolean getAusgenommen() {
		return this.ausgenommen;
	}
	@Convert(converter = BooleanToStringConverter.class)
	public void setAusgenommen(Boolean ausgenommen) {
		this.ausgenommen = ausgenommen;
	}

	@Column(name = "SORTIER_NR", precision = 22)
	public BigDecimal getSortierNr() {
		return this.sortierNr;
	}

	public void setSortierNr(BigDecimal sortierNr) {
		this.sortierNr = sortierNr;
	}

}
