package de.dredlich.psm.api.datenschubser.model.awg;

import de.dredlich.psm.api.datenschubser.model.pk.AwgPartnerAufwandId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

import java.math.BigDecimal;

/**
 * AwgPartnerAufwand generated by hbm2java
 */
@Entity
@Table(name = "AWG_PARTNER_AUFWAND")
public class AwgPartnerAufwand implements java.io.Serializable, ISetItemPK {

	private AwgPartnerAufwandId id;
	private BigDecimal MAufwand;
	private String MAufwandEinheit;

	public AwgPartnerAufwand() {}

	public AwgPartnerAufwand(AwgPartnerAufwandId id,
							 BigDecimal MAufwand,
							 String MAufwandEinheit)
	{
		this.id = id;
		this.MAufwand = MAufwand;
		this.MAufwandEinheit = MAufwandEinheit;
	}

	@EmbeddedId

	@AttributeOverrides({
		@AttributeOverride(name = "awgId", column = @Column(name = "AWG_ID", nullable = false, length = 16)),
		@AttributeOverride(name = "partnerKennr", column = @Column(name = "PARTNER_KENNR", nullable = false, length = 9)),
		@AttributeOverride(name = "aufwandbedingung", column = @Column(name = "AUFWANDBEDINGUNG", nullable = false, length = 20))
	})
	public AwgPartnerAufwandId getId() {
		return this.id;
	}

	public void setId(AwgPartnerAufwandId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (AwgPartnerAufwandId) id;
	}

	@Column(name = "M_AUFWAND", precision = 10, scale = 4)
	public BigDecimal getMAufwand() {
		return this.MAufwand;
	}

	public void setMAufwand(BigDecimal MAufwand) {
		this.MAufwand = MAufwand;
	}

	@Column(name = "M_AUFWAND_EINHEIT", length = 20)
	public String getMAufwandEinheit() {
		return this.MAufwandEinheit;
	}

	public void setMAufwandEinheit(String MAufwandEinheit) {
		this.MAufwandEinheit = MAufwandEinheit;
	}

}
