package de.dredlich.psm.api.datenschubser.model.awg;

import de.dredlich.psm.api.datenschubser.model.pk.AwgPartnerId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * AwgPartner generated by hbm2java
 */
@Entity
@Table(name = "AWG_PARTNER")
public class AwgPartner implements java.io.Serializable, ISetItemPK {

	private AwgPartnerId id;
	private String mischungArt;

	public AwgPartner() {
	}

	public AwgPartner(AwgPartnerId id, String mischungArt) {
		this.id = id;
		this.mischungArt = mischungArt;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "awgId", column = @Column(name = "AWG_ID", nullable = false, length = 16)),
		@AttributeOverride(name = "partnerKennr", column = @Column(name = "PARTNER_KENNR", nullable = false, length = 9))
	})
	public AwgPartnerId getId() {
		return this.id;
	}
	public void setId(AwgPartnerId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (AwgPartnerId) id;
	}

	@Column(name = "MISCHUNG_ART", length = 20)
	public String getMischungArt() {
		return this.mischungArt;
	}
	public void setMischungArt(String mischungArt) {
		this.mischungArt = mischungArt;
	}

}
