package de.dredlich.psm.api.datenschubser.model.awg;

import de.dredlich.psm.api.datenschubser.model.pk.AwgVerwendungszweckId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * AwgVerwendungszweck generated by hbm2java
 */
@Entity
@Table(name = "AWG_VERWENDUNGSZWECK")
public class AwgVerwendungszweck implements java.io.Serializable, ISetItemPK {

	private AwgVerwendungszweckId id;

	public AwgVerwendungszweck() {
	}

	public AwgVerwendungszweck(AwgVerwendungszweckId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "awgId", column = @Column(name = "AWG_ID", nullable = false, length = 16)),
			@AttributeOverride(name = "verwendungszweck", column = @Column(name = "VERWENDUNGSZWECK", nullable = false, length = 20)) })
	public AwgVerwendungszweckId getId() {
		return this.id;
	}

	public void setId(AwgVerwendungszweckId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (AwgVerwendungszweckId) id;
	}

}
