package de.dredlich.psm.api.datenschubser.model.awg;

import de.dredlich.psm.api.datenschubser.model.pk.AwgWartezeitAusgKulturId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * AwgWartezeitAusgKultur generated by hbm2java
 */
@Entity
@Table(name = "AWG_WARTEZEIT_AUSG_KULTUR")
public class AwgWartezeitAusgKultur implements java.io.Serializable, ISetItemPK {

	private AwgWartezeitAusgKulturId id;

	public AwgWartezeitAusgKultur() { }

	public AwgWartezeitAusgKultur(AwgWartezeitAusgKulturId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "awgWartezeitNr", column = @Column(name = "AWG_WARTEZEIT_NR", precision = 22, scale = 0)),
		@AttributeOverride(name = "kultur", column = @Column(name = "KULTUR", length = 20))
	})
	public AwgWartezeitAusgKulturId getId() {
		return this.id;
	}

	public void setId(AwgWartezeitAusgKulturId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (AwgWartezeitAusgKulturId) id;
	}

}
