package de.dredlich.psm.api.datenschubser.model.awg;

import de.dredlich.psm.api.datenschubser.model.pk.AwgZeitpunktId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

import java.math.BigDecimal;

/**
 * AwgZeitpunkt generated by hbm2java
 */
@Entity
@Table(name = "AWG_ZEITPUNKT")
public class AwgZeitpunkt implements java.io.Serializable, ISetItemPK {

	private AwgZeitpunktId id;
	private BigDecimal sortierNr;
	private String operandZuVorher;

	public AwgZeitpunkt() {
	}

	public AwgZeitpunkt(AwgZeitpunktId id, Awg awg, BigDecimal sortierNr, String operandZuVorher) {
		this.id = id;
		this.sortierNr = sortierNr;
		this.operandZuVorher = operandZuVorher;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "awgId", column = @Column(name = "AWG_ID", nullable = false, length = 16)),
		@AttributeOverride(name = "zeitpunkt", column = @Column(name = "ZEITPUNKT", nullable = false, length = 20))
	})
	public AwgZeitpunktId getId() {
		return this.id;
	}

	public void setId(AwgZeitpunktId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (AwgZeitpunktId) id;
	}

	@Column(name = "SORTIER_NR", precision = 22)
	public BigDecimal getSortierNr() {
		return this.sortierNr;
	}

	public void setSortierNr(BigDecimal sortierNr) {
		this.sortierNr = sortierNr;
	}

	@Column(name = "OPERAND_ZU_VORHER", length = 4)
	public String getOperandZuVorher() {
		return this.operandZuVorher;
	}

	public void setOperandZuVorher(String operandZuVorher) {
		this.operandZuVorher = operandZuVorher;
	}

}
