package de.dredlich.psm.api.datenschubser.model.awg;

import de.dredlich.psm.api.datenschubser.model.ISetItem;
import jakarta.persistence.*;

import java.util.Date;

/**
 * AwgZulassung generated by hbm2java
 */
@Entity
@Table(name = "AWG_ZULASSUNG")
public class AwgZulassung implements ISetItem {

	private String awgId;
	private Date zulEnde;

	public AwgZulassung() {
	}

	public AwgZulassung(Date zulEnde) {
		this.zulEnde = zulEnde;
	}

	@Id
	@Column(name = "AWG_ID", unique = true, nullable = false, length = 16)
	public String getAwgId() {
		return this.awgId;
	}

	public void setAwgId(String awgId) {
		this.awgId = awgId;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "ZUL_ENDE", length = 7)
	public Date getZulEnde() {
		return this.zulEnde;
	}

	public void setZulEnde(Date zulEnde) {
		this.zulEnde = zulEnde;
	}

}
