package de.dredlich.psm.api.datenschubser.model;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import de.dredlich.psm.api.datenschubser.model.pk.AntragId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

import java.io.Serializable;


/**
 * Antrag generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "ANTRAG")
public class Antrag  implements Serializable, ISetItemPK {


	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
		@AttributeOverride(name = "antragnr", column = @Column(name = "ANTRAGNR", nullable = false, length = 2))
	})
	private AntragId antragId;

	@Column(name = "ANTRAGSTELLER", length = 20)
	private String antragsteller;

	@Column(name = "ANTRAGSTELLER_NR", precision = 22)
	private Long antragstellerNr;

	public Antrag() {}

	public Antrag(AntragId antragId, String antragsteller, Long antragstellerNr) {
		this.antragId = antragId;
		this.antragsteller = antragsteller;
		this.antragstellerNr = antragstellerNr;
	}

	public ICompPK getId() {
		return antragId;
	}

	public AntragId getAntragId() {
		return antragId;
	}

	public void setID(ICompPK id){
		this.antragId = (AntragId) id;
	}

	public void setAntragId(AntragId antragId) {
		this.antragId = antragId;
	}

	public String getAntragsteller() {
		return this.antragsteller;
	}

	public void setAntragsteller(String antragsteller) {
		this.antragsteller = antragsteller;
	}

	public Long getAntragstellerNr() {
		return this.antragstellerNr;
	}

	public void setAntragstellerNr(Long antragstellerNr) {
		this.antragstellerNr = antragstellerNr;
	}

}
