package de.dredlich.psm.api.datenschubser.model;



import jakarta.persistence.*;
import java.math.BigDecimal;

/**
 * Auflagen generated by hbm2java
 */
@Entity
@Table(name = "AUFLAGEN")
public class Auflagen implements ISetItem {

	private BigDecimal auflagenr;
	private String auflage;
	private String weitereBedingung;
	private String ebene;
	private String kultur;
	private String anwendungstechnik;
	private BigDecimal abstand;


	@Column(name = "ANWENDBEST", nullable = false, length = 1)
	private Boolean anwendbest;
	private String reduAbstand;

	public Auflagen() { }

	public Auflagen(BigDecimal auflagenr, String auflage, Boolean anwendbest) {
		this.auflagenr = auflagenr;
		this.auflage = auflage;
		this.anwendbest = anwendbest;
	}

	public Auflagen(BigDecimal auflagenr,
					String auflage,
					String weitereBedingung,
					String ebene,
					String kultur,
					String anwendungstechnik,
					BigDecimal abstand,
					Boolean anwendbest,
					String reduAbstand) {
		this.auflagenr = auflagenr;
		this.auflage = auflage;
		this.weitereBedingung = weitereBedingung;
		this.ebene = ebene;
		this.kultur = kultur;
		this.anwendungstechnik = anwendungstechnik;
		this.abstand = abstand;
		this.anwendbest = anwendbest;
		this.reduAbstand = reduAbstand;
	}

	@Id
	@Column(name = "AUFLAGENR", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getAuflagenr() {
		return this.auflagenr;
	}

	public void setAuflagenr(BigDecimal auflagenr) {
		this.auflagenr = auflagenr;
	}

	@Column(name = "AUFLAGE", nullable = false, length = 20)
	public String getAuflage() {
		return this.auflage;
	}

	public void setAuflage(String auflage) {
		this.auflage = auflage;
	}

	@Column(name = "WEITERE_BEDINGUNG", length = 20)
	public String getWeitereBedingung() {
		return this.weitereBedingung;
	}

	public void setWeitereBedingung(String weitereBedingung) {
		this.weitereBedingung = weitereBedingung;
	}

	@Column(name = "EBENE", length = 16)
	public String getEbene() {
		return this.ebene;
	}

	public void setEbene(String ebene) {
		this.ebene = ebene;
	}

	@Column(name = "KULTUR", length = 20)
	public String getKultur() {
		return this.kultur;
	}

	public void setKultur(String kultur) {
		this.kultur = kultur;
	}

	@Column(name = "ANWENDUNGSTECHNIK", length = 20)
	public String getAnwendungstechnik() {
		return this.anwendungstechnik;
	}

	public void setAnwendungstechnik(String anwendungstechnik) {
		this.anwendungstechnik = anwendungstechnik;
	}

	@Column(name = "ABSTAND", precision = 38, scale = 0)
	public BigDecimal getAbstand() {
		return this.abstand;
	}

	public void setAbstand(BigDecimal abstand) {
		this.abstand = abstand;
	}

	public Boolean getAnwendbest() {
		return this.anwendbest;
	}

	//@Convert(converter=BooleanToStringConverter.class)
	public void setAnwendbest(Boolean anwendbest) {
		this.anwendbest = anwendbest;
	}

	@Column(name = "REDU_ABSTAND", length = 40)
	public String getReduAbstand() {
		return this.reduAbstand;
	}

	public void setReduAbstand(String reduAbstand) {
		this.reduAbstand = reduAbstand;
	}

}
