package de.dredlich.psm.api.datenschubser.model;

import de.dredlich.psm.api.datenschubser.model.pk.AuflageReduId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * AuflageRedu generated by hbm2java
 */
@Entity
@Table(name = "AUFLAGE_REDU")
public class AuflageRedu implements java.io.Serializable, ISetItemPK {

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "auflagenr", column = @Column(name = "AUFLAGENR", nullable = false, precision = 22)),
		@AttributeOverride(name = "kategorie", column = @Column(name = "KATEGORIE", nullable = false, length = 20)),
		@AttributeOverride(name = "reduAbstand", column = @Column(name = "REDU_ABSTAND", length = 5))
	})
	private AuflageReduId auflageReduId;

	public AuflageRedu() { }

	public AuflageRedu(AuflageReduId auflageReduId) {
		this.auflageReduId = auflageReduId;
	}

	public ICompPK getId() {
		return this.auflageReduId;
	}

	public void setId(AuflageReduId auflageReduId) {
		this.auflageReduId = auflageReduId;
	}

	@Override
	public void setID(ICompPK id) {
		this.auflageReduId = (AuflageReduId) id;
	}


}
