package de.dredlich.psm.api.datenschubser.model;

import de.dredlich.psm.api.datenschubser.model.pk.HinweisId;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import jakarta.persistence.*;

/**
 * Hinweis generated by hbm2java
 */
@Entity
@Table(name = "HINWEIS")
public class Hinweis implements java.io.Serializable, ISetItemPK {

	private HinweisId id;

	public Hinweis() {
	}

	public Hinweis(HinweisId id) {
		this.id = id;
	}


	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "ebene", column = @Column(name = "EBENE", nullable = false, length = 16)),
			@AttributeOverride(name = "hinweis", column = @Column(name = "HINWEIS", nullable = false, length = 20)) })
	public HinweisId getId() {
		return this.id;
	}

	public void setId(HinweisId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (HinweisId) id;
	}

}
