package de.dredlich.psm.api.datenschubser.model;
// Generated 21.08.2021, 19:02:40 by Hibernate Tools 5.2.12.Final

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;

/**
 * Kodeliste generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"hibernateLazyInitializer", "handler"})
@Table(name = "KODELISTE")
public class Kodeliste implements ISetItem {

	private Short kodeliste;
	private String listenname;
	private Set<Kode> kodes = new HashSet<Kode>(0);

	public Kodeliste() {
	}

	public Kodeliste(short kodeliste, String listenname) {
		this.kodeliste = kodeliste;
		this.listenname = listenname;
	}

	public Kodeliste(short kodeliste, String listenname, Set<Kode> kodes) {
		this.kodeliste = kodeliste;
		this.listenname = listenname;
		this.kodes = kodes;
	}

	@Id
	@Column(name = "KODELISTE", unique = true, nullable = false, precision = 3, scale = 0)
	public Short getKodeliste() {
		return this.kodeliste;
	}

	public void setKodeliste(Short kodeliste) {
		this.kodeliste = kodeliste;
	}

	@Column(name = "LISTENNAME", nullable = false, length = 200)
	public String getListenname() {
		return this.listenname;
	}

	public void setListenname(String listenname) {
		this.listenname = listenname;
	}

	@JsonBackReference
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "kodeliste")
	public Set<Kode> getKodes() {
		return this.kodes;
	}

	public void setKodes(Set<Kode> kodes) {
		this.kodes = kodes;
	}

}
