package de.dredlich.psm.api.datenschubser.model;

import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import de.dredlich.psm.api.datenschubser.model.pk.KodelisteFeldnameId;
import jakarta.persistence.*;

/**
 * KodelisteFeldname generated by hbm2java
 */
@Entity
@Table(name = "KODELISTE_FELDNAME")
public class KodelisteFeldname implements java.io.Serializable, ISetItemPK {

	private KodelisteFeldnameId id;

	public KodelisteFeldname() {
	}

	public KodelisteFeldname(KodelisteFeldnameId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "kodeliste", column = @Column(name = "KODELISTE", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "tabelle", column = @Column(name = "TABELLE", nullable = false, length = 30)),
			@AttributeOverride(name = "feldname", column = @Column(name = "FELDNAME", nullable = false, length = 30)) })
	public KodelisteFeldnameId getId() {
		return this.id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (KodelisteFeldnameId) id;
	}
	public void setId(KodelisteFeldnameId id) {
		this.id = id;
	}

}
