package de.dredlich.psm.api.datenschubser.model;

import com.fasterxml.jackson.annotation.JsonManagedReference;
import de.dredlich.psm.api.datenschubser.converter.BooleanToStringConverter;
import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import de.dredlich.psm.api.datenschubser.model.pk.KodeId;
import jakarta.persistence.*;

/**
 * Kode generated by hbm2java
 */
@Entity
@Table(name = "KODE")
public class Kode implements java.io.Serializable, ISetItemPK {

	private KodeId id;
	private Kodeliste kodeliste;
	private String kodetext;
	private Boolean sperre;

	public Kode() {
	}

	public Kode(KodeId id, Kodeliste kodeliste, String kodetext) {
		this.id = id;
		this.kodeliste = kodeliste;
		this.kodetext = kodetext;
	}

	public Kode(KodeId id, Kodeliste kodeliste,
				String kodetext, Boolean sperre) {
		this.id = id;
		this.kodeliste = kodeliste;
		this.kodetext = kodetext;
		this.sperre = sperre;
	}

	@EmbeddedId

	@AttributeOverrides({
		@AttributeOverride(name = "kode", column = @Column(name = "KODE", nullable = false, length = 20)),
		@AttributeOverride(name = "kodeliste", column = @Column(name = "KODELISTE", nullable = false, precision = 3, scale = 0)),
		@AttributeOverride(name = "sprache", column = @Column(name = "SPRACHE", nullable = false, length = 20))
	})
	public KodeId getId() {
		return this.id;
	}

	public void setId(KodeId id) {
		this.id = id;
	}
	@Override
	public void setID(ICompPK id) {
		this.id = (KodeId) id;
	}

	@JsonManagedReference
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "KODELISTE", nullable = false, insertable = false, updatable = false)
	public Kodeliste getKodeliste() {
		return this.kodeliste;
	}

	public void setKodeliste(Kodeliste kodeliste) {
		this.kodeliste = kodeliste;
	}

	@Column(name = "KODETEXT", nullable = false, length = 2000)
	public String getKodetext() {
		return this.kodetext;
	}

	public void setKodetext(String kodetext) {
		this.kodetext = kodetext;
	}

	@Convert(converter = BooleanToStringConverter.class)
	@Column(name = "SPERRE", length = 1)
	public Boolean getSperre() {
		return this.sperre;
	}

	@Convert(converter = BooleanToStringConverter.class)
	public void setSperre(Boolean sperre) {
		this.sperre = sperre;
	}

}
