package de.dredlich.psm.api.datenschubser.model;

import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import de.dredlich.psm.api.datenschubser.model.pk.ParallelimportAbgelaufenId;
import jakarta.persistence.*;

import java.math.BigDecimal;

/**
 * ParallelimportAbgelaufen generated by hbm2java
 */
@Entity
@Table(name = "PARALLELIMPORT_ABGELAUFEN")
public class ParallelimportAbgelaufen implements java.io.Serializable, ISetItemPK {

	private ParallelimportAbgelaufenId id;

	private BigDecimal importeurNr;

	private String importeur;

	public ParallelimportAbgelaufen() {
	}

	public ParallelimportAbgelaufen(ParallelimportAbgelaufenId id, BigDecimal importeurNr) {
		this.id = id;
		this.importeurNr = importeurNr;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "piPsmnr", column = @Column(name = "PI_PSMNR", nullable = false, length = 7)),
			@AttributeOverride(name = "piReferenzKennr", column = @Column(name = "PI_REFERENZ_KENNR", length = 9)),
			@AttributeOverride(name = "piKennziffer", column = @Column(name = "PI_KENNZIFFER", length = 3)),
			@AttributeOverride(name = "piStatus", column = @Column(name = "PI_STATUS", length = 20)),
			@AttributeOverride(name = "importeurTxt", column = @Column(name = "IMPORTEUR_TXT", length = 300)),
			@AttributeOverride(name = "piMittelname", column = @Column(name = "PI_MITTELNAME", length = 110)),
			@AttributeOverride(name = "gueltig", column = @Column(name = "GUELTIG", length = 7)),
			@AttributeOverride(name = "piBescheidnr", column = @Column(name = "PI_BESCHEIDNR", length = 2)),
			@AttributeOverride(name = "bescheidDatum", column = @Column(name = "BESCHEID_DATUM", length = 7)),
			@AttributeOverride(name = "bescheinigung", column = @Column(name = "BESCHEINIGUNG", length = 1)),
			@AttributeOverride(name = "mittelname", column = @Column(name = "MITTELNAME", length = 110)),
	})
	public ParallelimportAbgelaufenId getId() {
		return this.id;
	}

	public void setId(ParallelimportAbgelaufenId id) {
		this.id = id;
	}
	@Override
	public void setID(ICompPK id) {
		this.id = (ParallelimportAbgelaufenId) id;
	}

	@Column(name = "IMPORTEUR_NR", precision = 22, scale = 0, nullable = true)
	public BigDecimal getImporteurNr() {
		return this.importeurNr;
	}

	public void setImporteurNr(BigDecimal importeurNr) {
		this.importeurNr = importeurNr;
	}

	@Column(name = "IMPORTEUR", length = 20, nullable = true)
	public String getImporteur() {
		return this.importeur;
	}

	public void setImporteur(String importeur) {
		this.importeur = importeur;
	}


}
