package de.dredlich.psm.api.datenschubser.model;

import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import de.dredlich.psm.api.datenschubser.model.pk.SchadorgGruppeId;
import jakarta.persistence.*;

/**
 * SchadorgGruppe generated by hbm2java
 */
@Entity
@Table(name = "SCHADORG_GRUPPE")
public class SchadorgGruppe implements java.io.Serializable, ISetItemPK {

	private SchadorgGruppeId id;

	public SchadorgGruppe() {
	}

	public SchadorgGruppe(SchadorgGruppeId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "schadorgGruppe", column = @Column(name = "SCHADORG_GRUPPE", nullable = false, length = 20)),
			@AttributeOverride(name = "schadorg", column = @Column(name = "SCHADORG", nullable = false, length = 20))})
	public SchadorgGruppeId getId() {
		return this.id;
	}

	public void setId(SchadorgGruppeId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (SchadorgGruppeId) id;
	}

}
