package de.dredlich.psm.api.datenschubser.model;

import de.dredlich.psm.api.datenschubser.model.pk.ICompPK;
import de.dredlich.psm.api.datenschubser.model.pk.ISetItemPK;
import de.dredlich.psm.api.datenschubser.model.pk.StaerkungVertriebId;
import jakarta.persistence.*;

/**
 * StaerkungVertrieb generated by hbm2java
 */
@Entity
@Table(name = "STAERKUNG_VERTRIEB")
public class StaerkungVertrieb implements java.io.Serializable, ISetItemPK {

	private StaerkungVertriebId id;

	public StaerkungVertrieb() {
	}

	public StaerkungVertrieb(StaerkungVertriebId id, Staerkung staerkung) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
		@AttributeOverride(name = "kennr", column = @Column(name = "KENNR", nullable = false, length = 9)),
		@AttributeOverride(name = "vertriebsfirma", column = @Column(name = "VERTRIEBSFIRMA", length = 20)),
		@AttributeOverride(name = "vertriebsfirmaNr", column = @Column(name = "VERTRIEBSFIRMA_NR", nullable = false, precision = 22, scale = 0))
	})
	public StaerkungVertriebId getId() {
		return this.id;
	}

	public void setId(StaerkungVertriebId id) {
		this.id = id;
	}

	@Override
	public void setID(ICompPK id) {
		this.id = (StaerkungVertriebId) id;
	}

}
