package de.dredlich.psm.api.datenschubser.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

import java.util.Date;

/**
 * Stand generated by hbm2java
 */
@Entity
@Table(name = "STAND")
public class Stand implements ISetItem
{
	private Date datum;

	public Stand() {}
	public Stand(Date datum) {
		this.datum = datum;
	}

	@Id
	@Column(name = "DATUM", nullable = false, length = 7)
	public Date getDatum() {
		return datum;
	}

	public void setDatum(Date datum) {
		this.datum = datum;
	}

}
