package de.dredlich.psm.api.datenschubser.model;

import de.dredlich.psm.api.datenschubser.converter.BooleanToStringConverter;

import jakarta.persistence.*;

/**
 * Wirkstoff generated by hbm2java
 */
@Entity
@Table(name = "WIRKSTOFF")
public class Wirkstoff implements ISetItem {

	private String wirknr;
	private String wirkstoffname;
	private String wirkstoffnameEn;
	private String kategorie;
	private Boolean genehmigt;

	public Wirkstoff() {
	}

	public Wirkstoff(String wirknr,
					 String wirkstoffname,
					 String wirkstoffnameEn,
					 String kategorie,
					 Boolean genehmigt)
	{
		this.wirknr = wirknr;
		this.wirkstoffname = wirkstoffname;
		this.wirkstoffnameEn = wirkstoffnameEn;
		this.kategorie = kategorie;
		this.genehmigt = genehmigt;
	}

	@Id

	@Column(name = "WIRKNR", unique = true, nullable = false, length = 4)
	public String getWirknr() {
		return this.wirknr;
	}

	public void setWirknr(String wirknr) {
		this.wirknr = wirknr;
	}

	@Column(name = "WIRKSTOFFNAME", nullable = false, length = 100)
	public String getWirkstoffname() {
		return this.wirkstoffname;
	}

	public void setWirkstoffname(String wirkstoffname) {
		this.wirkstoffname = wirkstoffname;
	}

	@Column(name = "WIRKSTOFFNAME_EN", length = 100)
	public String getWirkstoffnameEn() {
		return this.wirkstoffnameEn;
	}

	public void setWirkstoffnameEn(String wirkstoffnameEn) {
		this.wirkstoffnameEn = wirkstoffnameEn;
	}

	@Column(name = "KATEGORIE", length = 20)
	public String getKategorie() {
		return this.kategorie;
	}

	public void setKategorie(String kategorie) {
		this.kategorie = kategorie;
	}

	@Convert(converter = BooleanToStringConverter.class)
	@Column(name = "GENEHMIGT", length = 1)
	public Boolean getGenehmigt() {
		return this.genehmigt;
	}

	@Convert(converter = BooleanToStringConverter.class)
	public void setGenehmigt(Boolean genehmigt) {
		this.genehmigt = genehmigt;
	}

}
